Solar System Project: src/generator.cpp File Reference
generator.cpp File Reference
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Macros
#define _USE_MATH_DEFINES
#define SPHERE "sphere"
#define CUBE "box"
#define CONE "cone"
#define PLANE "plane"
Functions
void points_vertex (const float x, const float y, const float z, unsigned int *pos, float points[])
void points_write (const char *filename, const unsigned int nVertices, const float points[])
void model_plane_vertices (const float length, const unsigned int divisions, float *points)
unsigned int model_plane_nVertices (const unsigned int divisions)
void model_plane_write (const char *filepath, const float length, const unsigned int divisions)
void model_cube_vertices (const float length, const unsigned int divisions, float points[])
unsigned int model_cube_nVertices (const unsigned int divisions)
void model_cube_write (const char *filepath, const float length, const unsigned int divisions)
static void model_cone_vertex (const float r, const float height, const float theta, const float h, unsigned int *pos, float *points)
void model_cone_vertices (const float r, const float height, const unsigned int slices, const unsigned int stacks, float points[])
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices)
void model_cone_write (const char *filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
static void model_sphere_vertex (const float r, const float theta, const float phi, unsigned int *pos, float *points)
static void model_sphere_vertices (const float r, const unsigned int slices, const unsigned int stacks, float points[])
static unsigned int model_sphere_nVertices (const unsigned int slices, const unsigned int stacks)
void model_sphere_write (const char *filepath, float radius, unsigned int slices, unsigned int stacks)
int main (int argc, char *argv[])
Macro Definition Documentation
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
CONE
#define CONE "cone"
CUBE
#define CUBE "box"
PLANE
#define PLANE "plane"
SPHERE
#define SPHERE "sphere"
Function Documentation
main()
int main (int argc, char * argv[])
{
    if (argc < 5) { printf("Not enough arguments"); }
    else {
        const char *filepath = argv[argc - 1];
        const char *polygon = argv[1];
        if (!strcmp(PLANE, polygon))
            model_plane_write(filepath, strtof(argv[2], nullptr), strtoul(argv[3], nullptr, 10));
        if (!strcmp(CUBE, polygon)) model_cube_write(filepath, atof(argv[2]), strtoul(argv[3], nullptr, 10));
        if (!strcmp(CONE, polygon))
            model_cone_write(filepath, atof(argv[2]), atof(argv[3]), atoi(argv[4]), atoi(argv[5]));
        if (!strcmp(SPHERE, polygon)) model_sphere_write(filepath, atof(argv[2]), atoi(argv[3]), atoi(argv[4]));
    }
    return 1;
}
References CONE, CUBE, model_cone_write(), model_cube_write(), model_plane_write(), model_sphere_write(), PLANE, and SPHERE.
model_cone_nVertices()
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices) inline static
{
    return slices * stacks * 9;
}
Referenced by model_cone_write().
model_cone_vertex()
static void model_cone_vertex (const float r, const float height, const float theta, const float h, unsigned int * pos, float * points) inline static
\begin{aligned} x &= r⋅\frac{h}{\textrm{height}} ⋅ \cos(θ)\\[2em] y &= h + \textrm{height}\\[2em] z &= r⋅\frac{h}{\textrm{height}} ⋅ \sin(θ) \end{aligned}
\begin{aligned} r &≥ 0\\ θ &∈ \left\{-π + i⋅s : s = \frac{2π}{\textrm{slices}} ∧ i ∈ \{0,...,\textrm{slices}\} \right\}\\ h &∈ \left\{- \textrm{height} + j⋅t : t = \frac{\textrm{height}}{\textrm{stacks}} ∧ j ∈ \{0,...,\textrm{stacks}\} \right\} \end{aligned}
{
    /*
       x = r ⋅ (h/height) ⋅ cos(θ)
       y = 2 ⋅ (height + h)
       z = r ⋅ (h/height) ⋅ sin(θ)
       r ≥ 0
       θ ∈ {-π      + i⋅s : s = 2π/slices      ∧ i ∈ {0,...,slices} }
       h ∈ {-height + j⋅t : t =  height/stacks ∧ j ∈ {0,...,stacks} }
       check:
           1. https://www.math3d.org/5gLCN9yBz
     */
    points_vertex(r * h / height * cos(theta), height + h, r * h / height * sin(theta), pos, points);
}
References points_vertex().
Referenced by model_cone_vertices().
model_cone_vertices()
void model_cone_vertices (const float r, const float height, const unsigned int slices, const unsigned int stacks, float points[])
{
    // https://www.math3d.org/5gLCN9yBz
    const float s = 2.0f * (float) M_PI / (float) slices;
    const float t = height / (float) stacks;
    const float theta = -M_PI;
    const float h = -height;
    unsigned int pos = 0;
    for (unsigned int m = 1; m <= slices; m++) {
        for (unsigned int n = 1; n <= stacks; n++) {
            float i = (float) m;
            float j = (float) n;
            //base
            points_vertex(0, 0, 0, &pos, points); //O
            model_cone_vertex(r, height, theta + s * (i - 1), h, &pos, points); //P1
            model_cone_vertex(r, height, theta + s * i, h, &pos, points); //P2
            model_cone_vertex(r, height, theta + s * i, h + t * (j - 1), &pos, points); // P2
            model_cone_vertex(r, height, theta + s * (i - 1), h + t * j, &pos, points); // P1'
            model_cone_vertex(r, height, theta + s * i, h + t * j, &pos, points); //P2'
            model_cone_vertex(r, height, theta + s * i, h + t * (j - 1), &pos, points); // P2
            model_cone_vertex(r, height, theta + s * (i - 1), h + t * (j - 1), &pos, points); // P1
            model_cone_vertex(r, height, theta + s * (i - 1), h + t * j, &pos, points); // P1'
        }
    }
}
References model_cone_vertex(), and points_vertex().
Referenced by model_cone_write().
model_cone_write()
void model_cone_write (const char * filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
{
    const unsigned int nVertices = model_cone_nVertices(stacks, slices);
    float points[3 * nVertices];
    model_cone_vertices(radius, height, slices, stacks, points);
    points_write(filepath, nVertices, points);
}
References model_cone_nVertices(), model_cone_vertices(), and points_write().
Referenced by main().
model_cube_nVertices()
unsigned int model_cube_nVertices (const unsigned int divisions)
{ return divisions * divisions * 36; }
Referenced by model_cube_write().
model_cube_vertices()
void model_cube_vertices (const float length, const unsigned int divisions, float points[])
{
    const float o = -length / 2.0f;
    const float d = length / (float) divisions;
    unsigned int pos = 0;
    for (unsigned int m = 1; m <= divisions; m++) {
        for (unsigned int n = 1; n <= divisions; n++) {
            float i = (float) m;
            float j = (float) n;
            // top
            points_vertex(o + d * (i - 1), -o, o + d * (j - 1), &pos, points); //P1
            points_vertex(o + d * (i - 1), -o, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * i, -o, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * i, -o, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * (i - 1), -o, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * i, -o, o + d * j, &pos, points); //P2
            // bottom
            points_vertex(o + d * (i - 1), o, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * (i - 1), o, o + d * (j - 1), &pos, points); //P1
            points_vertex(o + d * i, o, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * (i - 1), o, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * i, o, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * i, o, o + d * j, &pos, points); //P2
            // left
            points_vertex(o, o + d * (i - 1), o + d * (j - 1), &pos, points); //P1
            points_vertex(o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
            points_vertex(o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
            points_vertex(o, o + d * i, o + d * j, &pos, points); //P2
            // right
            points_vertex(-o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
            points_vertex(-o, o + d * (i - 1), o + d * (j - 1), &pos, points); //P1
            points_vertex(-o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(-o, o + d * (i - 1), o + d * j, &pos, points); //P1'z
            points_vertex(-o, o + d * i, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(-o, o + d * i, o + d * j, &pos, points); //P2
            // front
            points_vertex(o + d * (i - 1), o + d * (j - 1), o, &pos, points); //P1
            points_vertex(o + d * (i - 1), o + d * j, o, &pos, points); //P1'z
            points_vertex(o + d * i, o + d * (j - 1), o, &pos, points); //P1'x
            points_vertex(o + d * i, o + d * (j - 1), o, &pos, points); //P1'x
            points_vertex(o + d * (i - 1), o + d * j, o, &pos, points); //P1'z
            points_vertex(o + d * i, o + d * j, o, &pos, points); //P2
            // back
            points_vertex(o + d * (i - 1), o + d * j, -o, &pos, points); //P1'z
            points_vertex(o + d * (i - 1), o + d * (j - 1), -o, &pos, points); //P1
            points_vertex(o + d * i, o + d * (j - 1), -o, &pos, points); //P1'x
            points_vertex(o + d * (i - 1), o + d * j, -o, &pos, points); //P1'z
            points_vertex(o + d * i, o + d * (j - 1), -o, &pos, points); //P1'x
            points_vertex(o + d * i, o + d * j, -o, &pos, points); //P2
        }
    }
}
References points_vertex().
Referenced by model_cube_write().
model_cube_write()
void model_cube_write (const char * filepath, const float length, const unsigned int divisions)
{
    const unsigned int nVertices = model_cube_nVertices(divisions);
    float points[3 * nVertices];
    model_cube_vertices(length, divisions, points);
    points_write(filepath, nVertices, points);
}
References model_cube_nVertices(), model_cube_vertices(), and points_write().
Referenced by main().
model_plane_nVertices()
unsigned int model_plane_nVertices (const unsigned int divisions) inline
{ return divisions * divisions * 12; }
Referenced by model_plane_write().
model_plane_vertices()
void model_plane_vertices (const float length, const unsigned int divisions, float * points)
{
    const float o = -length / 2.0f;
    const float d = length / (float) divisions;
    unsigned int pos = 0;
    for (unsigned int m = 1; m <= divisions; m++) {
        for (unsigned int n = 1; n <= divisions; n++) {
            float i = (float) m;
            float j = (float) n;
            points_vertex(o + d * (i - 1), 0, o + d * (j - 1), &pos, points); //P1
            points_vertex(o + d * (i - 1), 0, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * i, 0, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * i, 0, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * (i - 1), 0, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * i, 0, o + d * j, &pos, points); //P2
            /*Cull face*/
            points_vertex(o + d * (i - 1), 0, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * (i - 1), 0, o + d * (j - 1), &pos, points); //P1
            points_vertex(o + d * i, 0, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * (i - 1), 0, o + d * j, &pos, points); //P1'z
            points_vertex(o + d * i, 0, o + d * (j - 1), &pos, points); //P1'x
            points_vertex(o + d * i, 0, o + d * j, &pos, points); //P2
        }
    }
}
References points_vertex().
Referenced by model_plane_write().
model_plane_write()
void model_plane_write (const char * filepath, const float length, const unsigned int divisions)
{
    const unsigned int nVertices = model_plane_nVertices(divisions);
    float points[3 * nVertices];
    model_plane_vertices(length, divisions, points);
    points_write(filepath, nVertices, points);
}
References model_plane_nVertices(), model_plane_vertices(), and points_write().
Referenced by main().
model_sphere_nVertices()
static unsigned int model_sphere_nVertices (const unsigned int slices, const unsigned int stacks) inline static
{
    return slices * stacks * 6;
}
Referenced by model_sphere_write().
model_sphere_vertex()
static void model_sphere_vertex (const float r, const float theta, const float phi, unsigned int * pos, float * points) inline static
{
    /*
        x = r ⋅ sin(θ)cos(φ)
        y = r ⋅ sin(φ)
        z = r ⋅ cos(θ)cos(φ)
        r ≥ 0
        θ ∈ {-π +   i⋅s : s = 2π/slices ∧ i ∈ {0,...,slices} }
        ϕ ∈ {-π/2 + j⋅t : t =  π/stacks ∧ j ∈ {0,...,stacks} }
        check
            1. https://www.math3d.org/EumEEZBKe
            2. https://www.math3d.org/zE4n6xayX
     */
    points_vertex(r * sin(theta) * cos(phi), r * sin(phi), r * cos(theta) * cos(phi), pos, points);
}
References points_vertex().
Referenced by model_sphere_vertices().
model_sphere_vertices()
static void model_sphere_vertices (const float r, const unsigned int slices, const unsigned int stacks, float points[]) static
{
    // https://www.math3d.org/EumEEZBKe
    // https://www.math3d.org/zE4n6xayX
    const float s = 2.0f * (float) M_PI / (float) slices;
    const float t = M_PI / (float) stacks;
    const float theta = -M_PI;
    const float phi = -M_PI / 2.0f;
    unsigned int pos = 0;
    for (unsigned int m = 1; m <= slices; m++) {
        for (unsigned int n = 1; n <= stacks; n++) {
            float i = (float) m;
            float j = (float) n;
            model_sphere_vertex(r, theta + s * (i - 1), phi + t * j, &pos, points); // P1'
            model_sphere_vertex(r, theta + s * i, phi + t * (j - 1), &pos, points); // P2
            model_sphere_vertex(r, theta + s * i, phi + t * j, &pos, points); //P2'
            model_sphere_vertex(r, theta + s * (i - 1), phi + t * (j - 1), &pos, points); // P1
            model_sphere_vertex(r, theta + s * i, phi + t * (j - 1), &pos, points); // P2
            model_sphere_vertex(r, theta + s * (i - 1), phi + t * j, &pos, points); // P1'
        }
    }
}
References model_sphere_vertex().
Referenced by model_sphere_write().
model_sphere_write()
void model_sphere_write (const char * filepath, float radius, unsigned int slices, unsigned int stacks)
{
    const unsigned int nVertices = model_sphere_nVertices(slices, stacks);
    float points[3 * nVertices];
    model_sphere_vertices(radius, slices, stacks, points);
    points_write(filepath, nVertices, points);
}
References model_sphere_nVertices(), model_sphere_vertices(), and points_write().
Referenced by main().
points_vertex()
void points_vertex (const float x, const float y, const float z, unsigned int * pos, float points[])
{
    points[*pos] = x;
    points[*pos + 1] = y;
    points[*pos + 2] = z;
    *pos += 3;
}
Referenced by model_cone_vertex(), model_cone_vertices(), model_cube_vertices(), model_plane_vertices(), and model_sphere_vertex().
points_write()
void points_write (const char * filename, const unsigned int nVertices, const float points[])
{
    FILE *fp = fopen(filename, "w");
    if (!fp) {
        fprintf(stderr, "failed to open file");
        exit(1);
    }
    fwrite(&nVertices, sizeof(unsigned int), 1, fp);
    fwrite(points, 3 * sizeof(float), nVertices, fp);
    fclose(fp);
}
Referenced by model_cone_write(), model_cube_write(), model_plane_write(), and model_sphere_write().