Solar System - demo scence: Points
Points
Generator
Functions
void points_vertex (const float x, const float y, const float z, unsigned int *pos, float points[])
void points_write (const char *filename, const unsigned int nVertices, const float points[])
void model_write (const char *const filename, const vector< vec3 > &vertices, const vector< vec3 > &normals, const vector< vec2 > &texture)
Detailed Description
Function Documentation
model_write()
void model_write (const char *const filename, const vector< vec3 > & vertices, const vector< vec3 > & normals, const vector< vec2 > & texture)
Definition at line 70 of file generator.cpp.
{
  FILE *fp = fopen (filename, "w");
  if (!fp)
    {
      fprintf (stderr, "failed to open file: %s", filename);
      exit (1);
    }
  assert(vertices.size () < INT_MAX);
  const int nVertices = vertices.size ();
  const int nNormals = normals.size ();
  const int nTextures = texture.size ();
  fwrite (&nVertices, sizeof (nVertices), 1, fp);
  fwrite (vertices.data (), sizeof (vertices.back ()), nVertices, fp);
  fwrite (normals.data (), sizeof (normals.back ()), nNormals, fp);
  fwrite (texture.data (), sizeof (texture.back ()), nTextures, fp);
  fclose (fp);
  cerr << "[generator] Wrote "
       << nVertices << " vertices, "
       << nNormals << " normals, "
       << nTextures << " textures to "
       << filename << endl;
}
Referenced by model_bezier_write(), model_cone_write(), model_cube_write(), model_plane_write(), and model_sphere_write().
points_vertex()
void points_vertex (const float x, const float y, const float z, unsigned int * pos, float points[])
Definition at line 46 of file generator.cpp.
{
  points[*pos] = x;
  points[*pos + 1] = y;
  points[*pos + 2] = z;
  *pos += 3;
}
points_write()
void points_write (const char * filename, const unsigned int nVertices, const float points[])
Definition at line 54 of file generator.cpp.
{
  FILE *fp = fopen (filename, "w");
  if (!fp)
    {
      fprintf (stderr, "failed to open file: %s", filename);
      exit (1);
    }
  fwrite (&nVertices, sizeof (unsigned int), 1, fp);
  fwrite (points, 3 * sizeof (float), nVertices, fp);
  fclose (fp);
}