Solar System - demo scence: Profile
Profile
Engine » Camera
Classes
struct profile_struct
Typedefs
typedef struct profile_struct profile_t
Enumerations
enum { EXPL = 0 , FPS , NPROFILES }
Functions
void changeProfile ()
void loadProfile (profile_t profile)
void defaultChangeSize (int w, int h)
Variables
int globalProfile = EXPL
bool globalProfileHasChanged = true
const profile_t profile [NPROFILES] = {globalProfile_EXPL, globalProfile_FPS}
Detailed Description
Typedef Documentation
profile_t
typedef struct profile_struct profile_t
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EXPL
FPS
NPROFILES
Definition at line 90 of file engine.cpp.
     {
  EXPL = 0, FPS, NPROFILES
};
Function Documentation
changeProfile()
void changeProfile ()
Definition at line 97 of file engine.cpp.
{
  globalProfileHasChanged = true;
  globalProfile = (globalProfile + 1) % NPROFILES;
}
References globalProfile, globalProfileHasChanged, and NPROFILES.
Referenced by explKeyboard(), and fpsKeyboard().
defaultChangeSize()
void defaultChangeSize (int w, int h)
Definition at line 1076 of file engine.cpp.
{
  // Prevent a divide by zero, when window is too short
  // (you can't make a window with zero width).
  if (h == 0)
    h = 1;
  // compute window's aspect ratio
  float ratio = (float) w * 1.0f / (float) h;
  // Set the projection matrix as current
  glMatrixMode (GL_PROJECTION);
  // Load Identity Matrix
  glLoadIdentity ();
  // Set the viewport to be the entire window
  glViewport (0, 0, w, h);
  // Set perspective
  gluPerspective (g::projection.x, ratio, g::projection.y, g::projection.z); //fox,near,far
  // return to the model view matrix mode
  glMatrixMode (GL_MODELVIEW);
  globalWidth = w;
  globalHeight = h;
}
References globalHeight, globalWidth, and g::projection.
loadProfile()
void loadProfile (profile_t profile)
Definition at line 103 of file engine.cpp.
{
  if (profile.keyboardFunc != nullptr)
    glutKeyboardFunc (profile.keyboardFunc);
  else
    glutKeyboardFunc (nullptr);
  if (profile.keyboardUpFunc != nullptr)
    glutKeyboardUpFunc (profile.keyboardUpFunc);
  else
    glutKeyboardUpFunc (nullptr);
  if (profile.specialFunc != nullptr)
    glutSpecialFunc (profile.specialFunc);
  else
    glutSpecialFunc (nullptr);
  if (profile.mouseFunc != nullptr)
    glutMouseFunc (profile.mouseFunc);
  else
    glutMouseFunc (nullptr);
  if (profile.motionFunc != nullptr)
    glutMotionFunc (profile.motionFunc);
  else
    glutMotionFunc (nullptr);
  if (profile.passiveMotionFunc != nullptr)
    glutPassiveMotionFunc (profile.passiveMotionFunc);
  else
    glutPassiveMotionFunc (nullptr);
  if (profile.reshapeFunc != nullptr)
    glutReshapeFunc (profile.reshapeFunc);
  if (profile.displayFunc != nullptr)
    glutDisplayFunc (profile.displayFunc);
  if (profile.timerFunc != nullptr)
    glutTimerFunc (0, profile.timerFunc, 0);
}
References profile_struct::displayFunc, profile_struct::keyboardFunc, profile_struct::keyboardUpFunc, profile_struct::motionFunc, profile_struct::mouseFunc, profile_struct::passiveMotionFunc, profile, profile_struct::reshapeFunc, profile_struct::specialFunc, and profile_struct::timerFunc.
Referenced by engine_run(), and renderScene().
Variable Documentation
globalProfile
int globalProfile = EXPL
Definition at line 94 of file engine.cpp.
Referenced by changeProfile(), engine_run(), and renderScene().
globalProfileHasChanged
bool globalProfileHasChanged = true
Definition at line 95 of file engine.cpp.
Referenced by changeProfile(), and renderScene().
profile
const profile_t profile[NPROFILES] = {globalProfile_EXPL, globalProfile_FPS}
Definition at line 853 of file engine.cpp.
Referenced by engine_run(), loadProfile(), and renderScene().