Solar System - demo scence: Models
Models
Operations
Functions
int operations_push_string_attribute (const XMLElement *const element, vector< float > &operations, const char *const attribute_name)
void operations_push_model (const XMLElement *const model, vector< float > &operations)
void operations_push_models (const XMLElement *const models, vector< float > &operations)
Detailed Description
Function Documentation
operations_push_model()
void operations_push_model (const XMLElement *const model, vector< float > & operations)
Definition at line 239 of file parsing.cpp.
{
  operations.push_back (BEGIN_MODEL);
  {
    const char *const model_name = model->Attribute ("file");
    if (model_name == nullptr)
      {
        cerr << "[parsing] [operations_push_string_attribute] failed: attrbute file does not exist" << endl;
        exit (EXIT_FAILURE);
      }
    cerr << "[parsing]: BEGIN_MODEL(" << model_name << ")" << endl;
    // generate model if specified
    const XMLElement *const generator = model->FirstChildElement ("generator");
    if (globalUsingGenerator && generator != nullptr)
      {
        cerr << "[parsing] generating model " << model_name << endl;
        const char *generator_argv[10];
        if (generator->QueryStringAttribute ("argv", generator_argv))
          {
          cerr << "failed parsing argv attribute of generator at model " << model_name << endl;
          exit (EXIT_FAILURE);
        }
      int stat;
      if ((stat = fork ()) == 0)
        {
          wordexp_t p;
          wordexp("generator", &p, WRDE_NOCMD | WRDE_UNDEF);
          if (wordexp (*generator_argv, &p, WRDE_NOCMD | WRDE_UNDEF | WRDE_APPEND))
            {
              cerr << "[parsing] failed argv expansion for model " << model_name << endl;
              exit(EXIT_FAILURE);
            }
          execv(globalGeneratorExecutable, p.we_wordv);
          perror ("[operations_push_model child] generator failed");
          _exit (EXIT_FAILURE);
        }
      else if (stat == -1)
        {
          perror ("[operations_push_model] ");
          exit (EXIT_FAILURE);
        }
        int status;
        wait (&status);
        if (WIFEXITED(status) && WEXITSTATUS(status))
          {
            perror ("[operations_push_model] generator failed");
            exit (EXIT_FAILURE);
          }
      }
    const int string_len = operations_push_string_attribute (model, operations, "file");
    if (string_len <= 0)
      {
        fprintf (stderr, "[parsing] filename is empty");
        exit (EXIT_FAILURE);
      }
  }
  //texture
  const XMLElement *const texture = model->FirstChildElement ("texture");
  if (texture != nullptr)
    {
      operations.push_back (TEXTURE);
      operations_push_string_attribute (texture, operations, "file");
    }
  //color (material colors)
  const XMLElement *const color = model->FirstChildElement ("color");
  if (color != nullptr)
    {
      const int n = 4;
      const char *const colorNames[n] = {"diffuse", "ambient", "specular", "emissive"};
      const operation_t colorTypes[n] = {DIFFUSE, AMBIENT, SPECULAR, EMISSIVE};
      for (int c = 0; c < n; ++c)
        {
          const XMLElement *const color_comp = color->FirstChildElement (colorNames[c]);
          if (color_comp != nullptr)
            {
              const float RGB_MAX = 255.0f;
              operations.push_back (colorTypes[c]);
              float R;
              if (color_comp->QueryFloatAttribute ("R", &R))
                {
                  cerr << "[parsing] failed parsing R component" << endl;
                  exit (EXIT_FAILURE);
                }
              float G;
              if (color_comp->QueryFloatAttribute ("G", &G))
                {
                  cerr << "[parsing] failed parsing G component" << endl;
                  exit (EXIT_FAILURE);
                }
              float B;
              if (color_comp->QueryFloatAttribute ("B", &B))
                {
                  cerr << "[parsing] failed parsing B component" << endl;
                  exit (EXIT_FAILURE);
                }
              operations.insert (operations.end (),
                                 {R / RGB_MAX, G / RGB_MAX, B / RGB_MAX});
            }
        }
      const XMLElement *const shininess = color->FirstChildElement ("shininess");
      if (shininess != nullptr)
        {
          operations.push_back (SHININESS);
          float value;
          if (shininess->QueryFloatAttribute ("value", &value))
            {
              cerr << "[parsing] failed parsing value attribute of shininess" << endl;
              exit (EXIT_FAILURE);
            }
          operations.push_back (value);
        }
    }
  operations.push_back (END_MODEL);
}
References AMBIENT, BEGIN_MODEL, DIFFUSE, EMISSIVE, END_MODEL, globalGeneratorExecutable, globalUsingGenerator, operations_push_string_attribute(), RGB_MAX, SHININESS, SPECULAR, and TEXTURE.
Referenced by operations_push_models().
operations_push_models()
void operations_push_models (const XMLElement *const models, vector< float > & operations)
Definition at line 363 of file parsing.cpp.
{
  const XMLElement *model = models->FirstChildElement ("model");
  do
    operations_push_model (model, operations);
  while ((model = model->NextSiblingElement ("model")));
}
References operations_push_model().
Referenced by operations_push_groups().
operations_push_string_attribute()
int operations_push_string_attribute (const XMLElement *const element, vector< float > & operations, const char *const attribute_name)
Definition at line 212 of file parsing.cpp.
{
  const char *const element_attribute_value = element->Attribute (attribute_name);
  if (element_attribute_value == nullptr)
    {
      cerr << "[parsing] [operations_push_string_attribute] failed: attrbute " << attribute_name << " does not exist"
           << endl;
      exit (EXIT_FAILURE);
    }
  if (access (element_attribute_value, F_OK))
    {
      cerr << "[parsing] file " << element_attribute_value << " not found" << endl;
      exit (EXIT_FAILURE);
    }
  int i = 0;
  do
    operations.push_back (element_attribute_value[i++]);
  while (element_attribute_value[i]);
  // add number of characters of element attribute string value
  operations.insert (operations.end () - i, (float) i);
  return i;
}
Referenced by operations_push_model().