Solar System - demo scence: Bezier
Bezier
Generator
Functions
vector< array< vec3, 16 > > read_Bezier (const char *const patch)
template<typename T >
static vec4 monic_3rd_polynomial_at (T n)
template<typename T >
static vec4 deriv_of_monic_3rd_polynomial_at (T n)
mat4x3 mat (const array< vec3, 4 > C)
void get_bezier_point_at (const auto u, const auto v, const array< vec3, 16 > &cp, vec3 &coordinate_in_3d_space, vec3 &normal)
static unsigned int model_bezier_patch_nVertices (const unsigned int tesselation)
static unsigned int model_bezier_surface_nVertices (const unsigned int number_of_patches, const unsigned int tesselation)
void get_bezier_patch (const array< vec3, 16 > control_points, const int int_tesselation, vector< vec3 > &vertices, vector< vec3 > &normals, vector< vec2 > &texture)
void get_bezier_surface (const vector< array< vec3, 16 > > &control_elements, const int tesselation, vector< vec3 > &vertices, vector< vec3 > &normals, vector< vec2 > &texture)
void model_bezier_write (const int tesselation, const char *const in_patch_file, const char *const out_3d_file)
Detailed Description
Function Documentation
deriv_of_monic_3rd_polynomial_at()
template<typename T > static vec4 deriv_of_monic_3rd_polynomial_at (T n) inline static
Definition at line 637 of file generator.cpp.
{
  return {3 * pow (n, 2), 2 * n, 1, 0};
}
Referenced by get_bezier_point_at().
get_bezier_patch()
void get_bezier_patch (const array< vec3, 16 > control_points, const int int_tesselation, vector< vec3 > & vertices, vector< vec3 > & normals, vector< vec2 > & texture)
Definition at line 706 of file generator.cpp.
{
  auto float_tesselation = (float) int_tesselation;
  const auto step = 1.0 / float_tesselation;
  for (int v = 0; v < int_tesselation; ++v)
    {
      for (int u = 0; u < int_tesselation; ++u)
        {
          for (auto e : {
              // upper triangle
              array<float, 2>{0, 1},
              array<float, 2>{0, 0},
              array<float, 2>{1, 0},
              // lower triangle
              array<float, 2>{1, 0},
              array<float, 2>{1, 1},
              array<float, 2>{0, 1},
          })
            {
              vec3 vertex, normal;
              get_bezier_point_at (u * step + step * e[0], v * step + step * e[1], control_points, vertex, normal);
              vertices.push_back (vertex);
              normals.push_back (normal);
              texture.emplace_back (-(u * step + step * e[0]), -(v * step + step * e[1]));
            }
        }
    }
  /*std::cout << "get_bezier_patch got:" << std::endl;
  for (auto p : pontos)
    std::cout << glm::to_string (p) << std::endl;*/
}
References get_bezier_point_at().
Referenced by get_bezier_surface().
get_bezier_point_at()
void get_bezier_point_at (const auto u, const auto v, const array< vec3, 16 > & cp, vec3 & coordinate_in_3d_space, vec3 & normal)
Parameters
[in] u first component of the 2d point.
[in] v second component of the 2d point.
[in] cp a set of control points that define the bezier patch.
[out] coordinate_in_3d_space cartesian three-dimensional coordinate of the point specified by Beziér patch coordinate.
[out] normal vector normal to the patch specified.
Definition at line 656 of file generator.cpp.
{
  // P_u notation at (slide 17)[Curves and Surfaces]
  // P(u,v) = UM(Pi0(P0u) + Pi1(P1u) + Pi2(P2u) Pi3(P3u)) based on (page 6)[CURVES AND SURFACES]
  // 4 sets of control points for 4 Bézier curves
  array<vec3, 4> C_i0 = {cp[0], cp[1], cp[2], cp[3]};
  array<vec3, 4> C_i1 = {cp[4], cp[5], cp[6], cp[7]};
  array<vec3, 4> C_i2 = {cp[8], cp[9], cp[10], cp[11]};
  array<vec3, 4> C_i3 = {cp[12], cp[13], cp[14], cp[15]};
  // calculate P_i(u) at each Bézier curve defined by Ci
  vec3 P0u, P1u, P2u, P3u, _;
  get_curve_point_at (u, Mb, C_i0, P0u, _);
  get_curve_point_at (u, Mb, C_i1, P1u, _);
  get_curve_point_at (u, Mb, C_i2, P2u, _);
  get_curve_point_at (u, Mb, C_i3, P3u, _);
  // Calculate vector tangent to u⃗
  const auto VM = monic_3rd_polynomial_at (v) * Mb;
  const auto U_prime = deriv_of_monic_3rd_polynomial_at (u);
  const auto tangent_u =
      (mat (C_i0) * VM[0] + mat (C_i1) * VM[1] + mat (C_i2) * VM[2] + mat (C_i3) * VM[3]) * Mb * U_prime;
  vec3 Puv, tangent_v;
  get_curve_point_at (v, Mb, {P0u, P1u, P2u, P3u}, Puv, tangent_v);
  normal = normalize (cross (tangent_u, tangent_v));
  coordinate_in_3d_space = Puv;
}
References deriv_of_monic_3rd_polynomial_at(), get_curve_point_at(), mat(), Mb, and monic_3rd_polynomial_at().
Referenced by get_bezier_patch().
get_bezier_surface()
void get_bezier_surface (const vector< array< vec3, 16 > > & control_elements, const int tesselation, vector< vec3 > & vertices, vector< vec3 > & normals, vector< vec2 > & texture)
Parameters
control_elements 4 vertices define a bezier curve and 4 bezier curves define a bezier patch. A set of bezier patches define a bezier surface. Therefore, each control element of a bezier surface requires 16 vertices.
Definition at line 750 of file generator.cpp.
{
  for (auto &control_element : control_elements)
    get_bezier_patch (control_element, tesselation, vertices, normals, texture);
}
References get_bezier_patch().
Referenced by model_bezier_write().
mat()
mat4x3 mat (const array< vec3, 4 > C)
Definition at line 642 of file generator.cpp.
{
  return {C[0], C[1], C[2], C[3]};
}
Referenced by get_bezier_point_at().
model_bezier_patch_nVertices()
static unsigned int model_bezier_patch_nVertices (const unsigned int tesselation) inline static
Definition at line 694 of file generator.cpp.
{
  return tesselation * tesselation * 6;
}
Referenced by model_bezier_surface_nVertices().
model_bezier_surface_nVertices()
static unsigned int model_bezier_surface_nVertices (const unsigned int number_of_patches, const unsigned int tesselation) inline static
Definition at line 699 of file generator.cpp.
{
  return model_bezier_patch_nVertices (tesselation) * number_of_patches;
}
References model_bezier_patch_nVertices().
Referenced by model_bezier_write().
model_bezier_write()
void model_bezier_write (const int tesselation, const char *const in_patch_file, const char *const out_3d_file)
Definition at line 762 of file generator.cpp.
{
  vector<array<vec3, 16>> control_points = read_Bezier (in_patch_file);
  const unsigned int nVertices = model_bezier_surface_nVertices (control_points.size (), tesselation);
  vector<vec3> vertices;
  vertices.reserve (nVertices);
  vector<vec3> normals;
  normals.reserve (nVertices);
  vector<vec2> texture;
  texture.reserve (nVertices);
  get_bezier_surface (control_points, tesselation, vertices, normals, texture);
  if (nVertices != vertices.size ())
    {
      cerr << nVertices << " = nVertices != vertices.size () = " << vertices.size () << endl;
      exit (EXIT_FAILURE);
    }
  model_write (out_3d_file, vertices, normals, texture);
}
References get_bezier_surface(), model_bezier_surface_nVertices(), model_write(), and read_Bezier().
Referenced by main().
monic_3rd_polynomial_at()
template<typename T > static vec4 monic_3rd_polynomial_at (T n) inline static
Definition at line 632 of file generator.cpp.
{
  return {pow (n, 3), pow (n, 2), n, 1};
}
Referenced by get_bezier_point_at().
read_Bezier()
vector< array< vec3, 16 > > read_Bezier (const char *const patch)
Definition at line 559 of file generator.cpp.
{
  string buffer;
  ifstream myFile;
  myFile.open (patch, ios::in | ios::out);
  getline (myFile, buffer);
  // Número de patches presentes no ficheiro.
  const int n_patches = stoi (buffer);
  // Vetor de vetores de índices.
  vector<vector<int>> patches;
  // Ciclo externo lê uma linha (patch) de cada vez
  for (int j = 0; j < n_patches; j++)
    {
      vector<int> patchIndexes;
      /*
      Ciclo interno lê os índices dos pontos de controlo de cada patch, sabendo que cada
      patch terá 16 pontos de controlo.
      */
      for (int i = 0; i < 15; i++)
        {
          getline (myFile, buffer, ',');
          patchIndexes.push_back (stoi (buffer));
        }
      getline (myFile, buffer);
      patchIndexes.push_back (stoi (buffer));
      patches.push_back (patchIndexes);
    }
  getline (myFile, buffer);
  // Número de pontos presentes no ficheiro.
  const int pts = stoi (buffer);
  // Vetor que guardará as coordenadas de pontos de controlo para superfície de Bézier.
  vector<vec3> control;
  for (int j = 0; j < pts; j++)
    {
      vec3 v;
      getline (myFile, buffer, ',');
      v[0] = stof (buffer);
      getline (myFile, buffer, ',');
      v[1] = stof (buffer);
      getline (myFile, buffer);
      v[2] = stof (buffer);
      control.push_back (v);
    }
  /*
  Percorrem-se os vetores que, para cada patch, guardam os seus índices de pontos de controlo.
  Para cada patch, constroi-se um vetor com as coordenadas dos seus pontos de controlo.
  */
  vector<array<vec3, 16>> pointsInPatches;
  for (auto &patche : patches)
    {
      array<vec3, 16> pointsInPatch{};
      for (int j = 0; j < 16; j++)
        {
          pointsInPatch[j] = control[patche[j]];
        }
      pointsInPatches.push_back (pointsInPatch);
    }
  myFile.close ();
  /*std::cout << "read_Bezier read:" << std::endl;
  for (auto arr : pointsInPatches)
    for (auto p : arr)
      std::cout << glm::to_string (p) << std::endl;*/
  return pointsInPatches;
}
Referenced by model_bezier_write().