Solar System - demo scence: Engine
Engine
Modules
Model
Camera
Input
Functions
void env_load_defaults ()
void changeSize (const int w, int h)
void redisplay ()
void renderGreenPlane ()
void renderScene ()
void xml_load_and_set_env (const char *const filename)
void engine_run (int argc, char **argv)
int main (int argc, char **argv)
Variables
const unsigned int DEFAULT_GLOBAL_ANGLE_STEP = 16
static float globalAngleStep = DEFAULT_GLOBAL_ANGLE_STEP
static float globalAngle = 0
static float globalRotateX = 0
static float globalRotateY = 0
static float globalRotateZ = 0
const unsigned int DEFAULT_GLOBAL_TRANSLATE_STEP = 1
static float globalTranslateStep = DEFAULT_GLOBAL_TRANSLATE_STEP
static float globalTranslateX = 0
static float globalTranslateY = 0
static float globalTranslateZ = 0
const unsigned int DEFAULT_GLOBAL_SCALE_STEP = 1
float globalScaleStep = DEFAULT_GLOBAL_SCALE_STEP
static float globalScaleX = 1
static float globalScaleY = 1
static float globalScaleZ = 1
int timebase = 0
int frame = 0
Detailed Description
Function Documentation
changeSize()
void changeSize (const int w, int h)
Definition at line 398 of file engine.cpp.
{
  // Prevent a divide by zero, when window is too short
  // (you can't make a window with zero width).
  if (h == 0)
    h = 1;
  // compute window's aspect ratio
  float ratio = (float) w * 1.0f / (float) h;
  // Set the projection matrix as current
  glMatrixMode (GL_PROJECTION);
  // Load Identity Matrix
  glLoadIdentity ();
  // Set the viewport to be the entire window
  glViewport (0, 0, w, h);
  // Set perspective
  gluPerspective (globalFOV, ratio, globalNear, globalFar); //fox,near,far
  // return to the model view matrix mode
  glMatrixMode (GL_MODELVIEW);
}
References globalFar, globalFOV, and globalNear.
Referenced by engine_run().
engine_run()
void engine_run (int argc, char ** argv)
Definition at line 1191 of file engine.cpp.
{
  if (argc != 2)
    {
      fprintf (stderr, "Engine only receives one argument, namley: the xml file defining what to draw\n");
      exit (EXIT_FAILURE);
    }
  // init GLUT and the window
  glutInit (&argc, argv);
  glutInitDisplayMode (GLUT_DEPTH | GLUT_DOUBLE | GLUT_RGBA);
  glutInitWindowPosition (100, 100);
  glutInitWindowSize (800, 800);
  glutCreateWindow ("engine");
  // Required callback registry
  glutDisplayFunc (renderScene);
  glutReshapeFunc (changeSize);
  // Callback registration for keyboard processing
  glutKeyboardFunc (keyboardFunc);
  // Callback registration for mouse processing
  glutMouseFunc (mouseFunc);
  glutMotionFunc (motionFunc);
  //  OpenGL settings
  glEnable (GL_DEPTH_TEST);
  // activate 2D texturing (slide 10) [class11]
  glEnable (GL_TEXTURE_2D);
  /*
   * For lighting to work properly when scales are applied to a model,
   * the following code below should be added to the initialization.
   * Activating this feature will result in normalizes normals after
   * applying the geometric transformations, and before applying lighting.
   */
  glEnable (GL_RESCALE_NORMAL);
  // activate lighting (done once in initialization) (slides 5) [class9]
  glEnable (GL_LIGHTING);
  // glEnable (GL_LIGHTi) done when needed
  // activate arrays (slide 12) [class11]
  glEnableClientState (GL_VERTEX_ARRAY);
  glEnableClientState (GL_NORMAL_ARRAY);
  glEnableClientState (GL_TEXTURE_COORD_ARRAY);
  /*
   * To allow for ambient colors to be reproduced without having
   * to activate the ambient component for all lights, the following
   * code should be added to the initialization:
   */
  const float amb[4] = {1.0f, 1.0f, 1.0f, 1.0f};
  glLightModelfv (GL_LIGHT_MODEL_AMBIENT, amb);
  // other details
  glEnable (GL_CULL_FACE);
  //glPolygonMode (GL_FRONT_AND_BACK, GL_FILL);
  glewInit ();
  xml_load_and_set_env (argv[1]);
  // enter GLUT's main cycle
  glutMainLoop ();
}
References changeSize(), keyboardFunc(), motionFunc(), mouseFunc(), renderScene(), and xml_load_and_set_env().
Referenced by main().
env_load_defaults()
void env_load_defaults ()
Definition at line 142 of file engine.cpp.
{
  /*rotation*/
  globalAngleStep = DEFAULT_GLOBAL_ANGLE_STEP;
  globalAngle = 0;
  globalRotateX = 0;
  globalRotateY = 0;
  globalRotateZ = 0;
  /*translation*/
  globalTranslateStep = DEFAULT_GLOBAL_TRANSLATE_STEP;
  globalTranslateX = 0;
  globalTranslateY = 0;
  globalTranslateZ = 0;
  /*scaling*/
  globalScaleStep = DEFAULT_GLOBAL_SCALE_STEP;
  globalScaleX = 1;
  globalScaleY = 1;
  globalScaleZ = 1;
  /*position*/
  globalEyeStep = DEFAULT_GLOBAL_EYE_STEP;
  globalEyeX = DEFAULT_GLOBAL_EYE_X;
  globalEyeY = DEFAULT_GLOBAL_EYE_Y;
  globalEyeZ = DEFAULT_GLOBAL_EYE_Z;
  globalRadius = DEFAULT_GLOBAL_RADIUS;
  globalAzimuth = DEFAULT_GLOBAL_AZIMUTH;
  globalElevation = DEFAULT_GLOBAL_ELEVATION;
  /*lookAt*/
  globalCenterStep = DEFAULT_GLOBAL_CENTER_STEP;
  globalCenterX = DEFAULT_GLOBAL_CENTER_X;
  globalCenterY = DEFAULT_GLOBAL_CENTER_Y;
  globalCenterZ = DEFAULT_GLOBAL_CENTER_Z;
  /*up*/
  globalUpStep = DEFAULT_GLOBAL_UP_STEP;
  globalUpX = DEFAULT_GLOBAL_UP_X;
  globalUpY = DEFAULT_GLOBAL_UP_Y;
  globalUpZ = DEFAULT_GLOBAL_UP_Z;
  /*projection*/
  globalFOV = DEFAULT_GLOBAL_FOV;
  globalNear = DEFAULT_GLOBAL_NEAR;
  globalFar = DEFAULT_GLOBAL_FAR;
}
References DEFAULT_GLOBAL_ANGLE_STEP, DEFAULT_GLOBAL_AZIMUTH, DEFAULT_GLOBAL_CENTER_STEP, DEFAULT_GLOBAL_CENTER_X, DEFAULT_GLOBAL_CENTER_Y, DEFAULT_GLOBAL_CENTER_Z, DEFAULT_GLOBAL_ELEVATION, DEFAULT_GLOBAL_EYE_STEP, DEFAULT_GLOBAL_EYE_X, DEFAULT_GLOBAL_EYE_Y, DEFAULT_GLOBAL_EYE_Z, DEFAULT_GLOBAL_FAR, DEFAULT_GLOBAL_FOV, DEFAULT_GLOBAL_NEAR, DEFAULT_GLOBAL_RADIUS, DEFAULT_GLOBAL_SCALE_STEP, DEFAULT_GLOBAL_TRANSLATE_STEP, DEFAULT_GLOBAL_UP_STEP, DEFAULT_GLOBAL_UP_X, DEFAULT_GLOBAL_UP_Y, DEFAULT_GLOBAL_UP_Z, globalAngle, globalAngleStep, globalAzimuth, globalCenterStep, globalCenterX, globalCenterY, globalCenterZ, globalElevation, globalEyeStep, globalEyeX, globalEyeY, globalEyeZ, globalFar, globalFOV, globalNear, globalRadius, globalRotateX, globalRotateY, globalRotateZ, globalScaleStep, globalScaleX, globalScaleY, globalScaleZ, globalTranslateStep, globalTranslateX, globalTranslateY, globalTranslateZ, globalUpStep, globalUpX, globalUpY, and globalUpZ.
Referenced by keyboardFunc(), and xml_load_and_set_env().
main()
int main (int argc, char ** argv)
command ::= xml_file
Definition at line 1266 of file engine.cpp.
{
  engine_run (argc, argv);
  return 1;
}
References engine_run().
redisplay()
void redisplay ()
Definition at line 799 of file engine.cpp.
{
  spherical2Cartesian (globalRadius, globalElevation, globalAzimuth, &globalEyeX, &globalEyeY, &globalEyeZ);
  glutPostRedisplay ();
}
References globalAzimuth, globalElevation, globalEyeX, globalEyeY, globalEyeZ, globalRadius, and spherical2Cartesian().
Referenced by keyboardFunc(), motionFunc(), mouseFunc(), and renderScene().
renderGreenPlane()
void renderGreenPlane ()
Definition at line 805 of file engine.cpp.
{
  glColor3f (0.2f, 0.8f, 0.2f);
  glBegin (GL_TRIANGLES);
  glVertex3f (100.0f, 0, -100.0f);
  glVertex3f (-100.0f, 0, -100.0f);
  glVertex3f (-100.0f, 0, 100.0f);
  glVertex3f (100.0f, 0, -100.0f);
  glVertex3f (-100.0f, 0, 100.0f);
  glVertex3f (100.0f, 0, 100.0f);
  glEnd ();
  glColor3f (1, 1, 1);
}
renderScene()
void renderScene (void)
Definition at line 821 of file engine.cpp.
{
  float fps;
  int time;
  char s[64];
  // clear buffers
  glClear (GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  // helps in avoiding rounding mistakes, discards old matrix, read more
  glLoadIdentity ();
  // set the camera
  gluLookAt (globalEyeX, globalEyeY, globalEyeZ,
             globalCenterX, globalCenterY, globalCenterZ,
             globalUpX, globalUpY, globalUpZ);
  draw_axes ();
  // put the geometric transformations here
  glRotatef (globalAngle, globalRotateX, globalRotateY, globalRotateZ);
  glTranslatef (globalTranslateX, globalTranslateY, globalTranslateZ);
  glScalef (globalScaleX, globalScaleY, globalScaleZ);
  // render models
  operations_render (globalOperations);
  // calculate and display frame rate
  frame++;
  time = glutGet (GLUT_ELAPSED_TIME);
  if (time - timebase > 1000)
    {
      fps = frame * 1000.0 / (time - timebase);
      timebase = time;
      frame = 0;
      sprintf (s, "FPS: %f6.2", fps);
      glutSetWindowTitle (s);
    }
  // End of frame
  redisplay ();
  glutSwapBuffers ();
}
References draw_axes(), frame, globalAngle, globalCenterX, globalCenterY, globalCenterZ, globalEyeX, globalEyeY, globalEyeZ, globalOperations, globalRotateX, globalRotateY, globalRotateZ, globalScaleX, globalScaleY, globalScaleZ, globalTranslateX, globalTranslateY, globalTranslateZ, globalUpX, globalUpY, globalUpZ, operations_render(), redisplay(), and timebase.
Referenced by engine_run().
xml_load_and_set_env()
void xml_load_and_set_env (const char *const filename)
Definition at line 864 of file engine.cpp.
{
  operations_load_xml (filename, globalOperations);
  operations_render (globalOperations);
  env_load_defaults ();
  cerr << "LOOK_AT(" << globalCenterX << "," << globalCenterY << "," << globalCenterZ << ")" << endl;
  cerr << "POSITION(" << globalEyeX << "," << globalEyeY << "," << globalEyeZ << ")" << endl;
}
References env_load_defaults(), globalCenterX, globalCenterY, globalCenterZ, globalEyeX, globalEyeY, globalEyeZ, globalOperations, operations_load_xml(), and operations_render().
Referenced by engine_run().
Variable Documentation
DEFAULT_GLOBAL_ANGLE_STEP
const unsigned int DEFAULT_GLOBAL_ANGLE_STEP = 16
Definition at line 34 of file engine.cpp.
Referenced by env_load_defaults().
DEFAULT_GLOBAL_SCALE_STEP
const unsigned int DEFAULT_GLOBAL_SCALE_STEP = 1
Definition at line 49 of file engine.cpp.
Referenced by env_load_defaults().
DEFAULT_GLOBAL_TRANSLATE_STEP
const unsigned int DEFAULT_GLOBAL_TRANSLATE_STEP = 1
Definition at line 42 of file engine.cpp.
Referenced by env_load_defaults().
frame
int frame = 0
Definition at line 820 of file engine.cpp.
Referenced by renderScene().
globalAngle
float globalAngle = 0 static
Definition at line 36 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalAngleStep
float globalAngleStep = DEFAULT_GLOBAL_ANGLE_STEP static
Definition at line 35 of file engine.cpp.
Referenced by env_load_defaults(), and keyboardFunc().
globalRotateX
float globalRotateX = 0 static
Definition at line 37 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalRotateY
float globalRotateY = 0 static
Definition at line 38 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalRotateZ
float globalRotateZ = 0 static
Definition at line 39 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalScaleStep
float globalScaleStep = DEFAULT_GLOBAL_SCALE_STEP
Definition at line 50 of file engine.cpp.
Referenced by env_load_defaults(), and keyboardFunc().
globalScaleX
float globalScaleX = 1 static
Definition at line 51 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalScaleY
float globalScaleY = 1 static
Definition at line 52 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalScaleZ
float globalScaleZ = 1 static
Definition at line 53 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalTranslateStep
float globalTranslateStep = DEFAULT_GLOBAL_TRANSLATE_STEP static
Definition at line 43 of file engine.cpp.
Referenced by env_load_defaults(), and keyboardFunc().
globalTranslateX
float globalTranslateX = 0 static
Definition at line 44 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalTranslateY
float globalTranslateY = 0 static
Definition at line 45 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
globalTranslateZ
float globalTranslateZ = 0 static
Definition at line 46 of file engine.cpp.
Referenced by env_load_defaults(), keyboardFunc(), and renderScene().
timebase
int timebase = 0
Definition at line 820 of file engine.cpp.
Referenced by renderScene().