Solar System - demo scence: Input
Input
Engine
Functions
void keyboardFunc (unsigned char key, int xmouse, int ymouse)
void mouseFunc (int button, int state, int x, int y)
void motionFunc (int x, int y)
Variables
int globalExplXPrev = 0
int globalExplYPrev = 0
Detailed Description
Function Documentation
keyboardFunc()
void keyboardFunc (unsigned char key, int xmouse, int ymouse)
Definition at line 874 of file engine.cpp.
{
  /*
      Rotation:
          x y z       x↓ y↓ z↓
          X Y Z       x↑ y↑ z↑
      angle:
          , .     θ-=s    θ+=s
          < >     s↓     s↑
      translation:
          q w e       y↓ z↑ y↑
          a s d       x↓ z↓ x↑
      scaling:
          u i o       y↓ z↑ y↑
          j k l       x↓ z↓ x↑
      background color: r g b R G B
      camera:
          1 2 3 ⎫       ! @ # ⎫        EyeX     EyeY     EyeZ
          4 5 6 ⎬↓      $ % ^ ⎬↑       CenterX  CenterY  CenterZ
          7 8 9 ⎭       & * ( ⎭        UpX      UpY      UpZ
   */
  switch (key)
    {
      /*Rotation*/
      case 'x':
        globalRotateX -= 1;
      break;
      case 'X':
        globalRotateX += 1;
      break;
      case 'y':
        globalRotateY -= 1;
      break;
      case 'Y':
        globalRotateY += 1;
      break;
      case 'z':
        globalRotateZ -= 1;
      break;
      case 'Z':
        globalRotateZ += 1;
      break;
      case ',':
        globalAngle -= globalAngleStep;
      break;
      case '.':
        globalAngle += globalAngleStep;
      break;
      case '<':
        globalAngleStep /= 2;
      break;
      case '>':
        globalAngleStep *= 2;
      break;
      /*translation*/
      case 'T':
        globalTranslateStep *= 2;
      break;
      case 't':
        if (globalTranslateStep > 1)
          globalTranslateStep /= 2;
      break;
      /*z-axis*/
      case 'w':
        globalTranslateZ += globalTranslateStep;
      break;
      case 's':
        globalTranslateZ -= globalTranslateStep;
      break;
      /*x-axis*/
      case 'a':
        globalTranslateX -= globalTranslateStep;
      break;
      case 'd':
        globalTranslateX += globalTranslateStep;
      break;
      /*y-axis*/
      case 'q':
        globalTranslateY -= globalTranslateStep;
      break;
      case 'e':
        globalTranslateY += globalTranslateStep;
      break;
      /*end of translation*/
      /*scaling*/
      /*z-axis*/
      case 'i':
        globalScaleZ += globalScaleStep;
      break;
      case 'k':
        globalScaleZ -= globalScaleStep;
      break;
      /*x-axis*/
      case 'j':
        globalScaleX -= globalScaleStep;
      break;
      case 'l':
        globalScaleX += globalScaleStep;
      break;
      /*y-axis*/
      case 'u':
        globalScaleY -= globalScaleStep;
      break;
      case 'o':
        globalScaleY += globalScaleStep;
      break;
      /*end of scaling*/
      /*camera*/
      case '`':
        globalEyeStep *= 2;
      break;
      case '~':
        if (globalEyeStep > 1)
          globalEyeStep /= 2;
      break;
      case '1':
        globalEyeX -= globalEyeStep;
      break;
      case '!':
        globalEyeX += globalEyeStep;
      break;
      case '2':
        globalEyeY -= globalEyeStep;
      break;
      case '@':
        globalEyeY += globalEyeStep;
      break;
      case '3':
        globalEyeZ -= globalEyeStep;
      break;
      case '#':
        globalEyeZ += globalEyeStep;
      break;
      case '4':
        globalCenterX -= globalCenterStep;
      break;
      case '$':
        globalCenterX += globalCenterStep;
      break;
      case '5':
        globalCenterY -= globalCenterStep;
      break;
      case '%':
        globalCenterY += globalCenterStep;
      break;
      case '6':
        globalCenterZ -= globalCenterStep;
      break;
      case '^':
        globalCenterZ += globalCenterStep;
      break;
      case '7':
        globalUpX -= globalUpStep;
      break;
      case '&':
        globalUpX += globalUpStep;
      break;
      case '8':
        globalUpY -= globalUpStep;
      break;
      case '*':
        globalUpY += globalUpStep;
      break;
      case '9':
        globalUpZ -= globalUpStep;
      break;
      case '(':
        globalUpZ += globalUpStep;
      break;
      /*reset environment*/
      case '0':
        env_load_defaults ();
      break;
      default:
        break;
    }
  redisplay (); //request display() call ASAP
}
References env_load_defaults(), globalAngle, globalAngleStep, globalCenterStep, globalCenterX, globalCenterY, globalCenterZ, globalEyeStep, globalEyeX, globalEyeY, globalEyeZ, globalRotateX, globalRotateY, globalRotateZ, globalScaleStep, globalScaleX, globalScaleY, globalScaleZ, globalTranslateStep, globalTranslateX, globalTranslateY, globalTranslateZ, globalUpStep, globalUpX, globalUpY, globalUpZ, and redisplay().
Referenced by engine_run().
motionFunc()
void motionFunc (int x, int y)
Definition at line 1159 of file engine.cpp.
{
  if (globalMouseLeftButton)
    {
      const double stepAlfa = 0.035;
      const double stepBeta = 0.035;
      if (x < globalExplXPrev)
        globalAzimuth += stepAlfa;
      else if (x > globalExplXPrev)
        globalAzimuth -= stepAlfa;
      if (y < globalExplYPrev)
        {
          globalElevation -= stepBeta;
          if (globalElevation < -1.5)
            globalElevation = -1.5;
        }
      else if (y > globalExplYPrev)
        {
          globalElevation += stepBeta;
          if (globalElevation > 1.5)
            globalElevation = 1.5;
        }
      globalExplXPrev = x;
      globalExplYPrev = y;
    }
  redisplay ();
}
References globalAzimuth, globalElevation, globalMouseLeftButton, globalExplXPrev, globalExplYPrev, and redisplay().
Referenced by engine_run().
mouseFunc()
void mouseFunc (int button, int state, int x, int y)
Definition at line 1078 of file engine.cpp.
{
  // Wheel reports as button 3(scroll up) and button 4(scroll down)
  if ((button == 3) || (button == 4)) // It's a wheel event
    {
      // Each wheel event reports like a button click, GLUT_DOWN then GLUT_UP
      if (state == GLUT_UP)
        return; // Disregard redundant GLUT_UP events
      if (button == 3)
        {
          globalRadius *= .8f;
          if (globalRadius < 1.0f)
            globalRadius = 1.0f;
        }
      else
        globalRadius *= 1.5;
      printf ("Scroll %s At %d %d\n", (button == 3) ? "Up" : "Down", x, y);
    }
  else
    {  // normal button event
      printf ("Button %s At %d %d\n", (state == GLUT_DOWN) ? "Down" : "Up", x, y);
      if (button == GLUT_LEFT_BUTTON)
        {
          if (state == GLUT_DOWN)
            {
              globalMouseLeftButton = true;
              globalExplXPrev = x;
              globalExplYPrev = y;
            }
          if (state == GLUT_UP)
            {
              globalMouseLeftButton = false;
            }
        }
      else if (button == GLUT_RIGHT_BUTTON)
        {
          if (state == GLUT_DOWN)
            {
              int window_width = glutGet (GLUT_WINDOW_WIDTH);
              int window_height = glutGet (GLUT_WINDOW_HEIGHT);
              GLbyte color[4];
              GLfloat depth;
              GLuint index;
              //glReadPixels (x, window_height - y - 1, 1, 1, GL_RGBA, GL_UNSIGNED_BYTE, color);
              glReadPixels (x, window_height - y - 1, 1, 1, GL_DEPTH_COMPONENT, GL_FLOAT, &depth);
              //glReadPixels (x, window_height - y - 1, 1, 1, GL_STENCIL_INDEX, GL_UNSIGNED_INT, &index);
              double ox, oy, oz;
              double model[16];
              glGetDoublev (GL_MODELVIEW_MATRIX, model);
              double proj[16];
              glGetDoublev (GL_PROJECTION_MATRIX, proj);
              int view[4];
              glGetIntegerv (GL_VIEWPORT, view);
              gluUnProject (x, window_height - y - 1, depth,
                            model,
                            proj,
                            view,
                            &ox, &oy, &oz);
              fprintf (stderr, "%d %d\n", x, y);
              //globalTranslateX = -ox;
              //globalTranslateZ = -oz;
              /*cartesian2Spherical (ox, globalEyeY, oz,
                                   &globalRadius, &globalAzimuth, &globalElevation);*/
              //              globalTranslateX = ox;
              //              globalTranslateZ = oz;
              globalCenterX = ox;
              globalCenterZ = oz;
              fprintf (stderr, "%f %f %f\n", ox, oy, oz);
            }
        }
    }
  redisplay ();
}
References globalCenterX, globalCenterZ, globalMouseLeftButton, globalRadius, globalExplXPrev, globalExplYPrev, and redisplay().
Referenced by engine_run().
Variable Documentation
globalExplXPrev
int globalExplXPrev = 0
Definition at line 1075 of file engine.cpp.
Referenced by motionFunc(), and mouseFunc().
globalExplYPrev
int globalExplYPrev = 0
Definition at line 1076 of file engine.cpp.
Referenced by motionFunc(), and mouseFunc().