Solar System - demo scence: Plane
Plane
Generator » Model
Functions
void model_plane_vertices (const float length, const unsigned int divisions, vector< vec3 > &vertices, vector< vec3 > &normals, vector< vec2 > &texture)
static unsigned int model_plane_nVertices (const unsigned int divisions)
void model_plane_write (const char *filepath, const float length, const unsigned int divisions)
Detailed Description
Function Documentation
model_plane_nVertices()
static unsigned int model_plane_nVertices (const unsigned int divisions) inline static
Definition at line 158 of file generator.cpp.
{ return divisions * divisions * 12; }
Referenced by model_plane_write().
model_plane_vertices()
void model_plane_vertices (const float length, const unsigned int divisions, vector< vec3 > & vertices, vector< vec3 > & normals, vector< vec2 > & texture)
Definition at line 108 of file generator.cpp.
{
  const float o = -length / 2.0f;
  const float d = length / (float) divisions;
  for (unsigned int uidiv1 = 1; uidiv1 <= divisions; ++uidiv1)
    {
      for (unsigned int uidiv2 = 1; uidiv2 <= divisions; ++uidiv2)
        {
          auto const fdiv1 = (float) uidiv1;
          auto const fdiv2 = (float) uidiv2;
          auto const fdivisions = (float) divisions;
          for (auto e : {
              array<float, 2>{-1, -1},//P1
              array<float, 2>{-1, 0},//P1'z
              array<float, 2>{0, -1},//P1'x
              array<float, 2>{0, -1},//P1'x
              array<float, 2>{-1, 0},//P1'z
              array<float, 2>{0, 0}})//P2
            {
              vertices.emplace_back (o + d * (fdiv1 + e[0]), 0, o + d * (fdiv2 + e[1]));
              normals.emplace_back (0, 1, 0);
              texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
            }
          /*Cull face*/
          for (auto e : {
              array<float, 2>{-1.0f, 0.0f},
              array<float, 2>{-1.0f, -1.0f},
              array<float, 2>{0.0f, -1.0f},
              array<float, 2>{-1.0f, 0.0f},
              array<float, 2>{0.0f, -1.0f},
              array<float, 2>{0.0f, 0.0f}})
            {
              vertices.emplace_back (o + d * (fdiv1 + e[0]), 0, o + d * (fdiv2 + e[1]));
              normals.emplace_back (0, -1, 0);
              texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
            }
        }
    }
}
Referenced by model_plane_write().
model_plane_write()
void model_plane_write (const char * filepath, const float length, const unsigned int divisions)
Definition at line 161 of file generator.cpp.
{
  const unsigned int nVertices = model_plane_nVertices (divisions);
  vector<vec3> vertices;
  vertices.reserve (nVertices);
  vector<vec3> normals;
  normals.reserve (nVertices);
  vector<vec2> texture;
  texture.reserve (nVertices);
  model_plane_vertices (length, divisions, vertices, normals, texture);
  model_write (filepath, vertices, normals, texture);
}
References model_plane_nVertices(), model_plane_vertices(), and model_write().
Referenced by main().