Solar System - demo scence: Rendering
Rendering
Operations
Functions
void operations_render (vector< float > &operations)
Detailed Description
Function Documentation
operations_render()
void operations_render (vector< float > & operations)
See Operations for the BNF of operations.
Definition at line 1122 of file engine.cpp.
{
  static bool isFirstTimeBeingExecuted = true;
  static bool hasPushedModels = false;
  static bool hasLoadedCurves = false;
  static vector<vector<vec3>> curves;
  static const float amb[4] = {0, 0, 0, 1};
  static const float spec[4] = {1, 1, 1, 1};
  static const float diff[4] = {1, 1, 1, 1};
  unsigned int model_num = 0;
  unsigned char nLights = 0;
  for (unsigned int i = 0; i < operations.size (); ++i)
    {
      assert(nLights < 8);
      switch ((int) operations[i])
        {
          case POSITION:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::cartesian[0] = operations[i + 1];
                  D::cartesian[1] = operations[i + 2];
                  D::cartesian[2] = operations[i + 3];
                  cerr << "POSITION(" << to_string (D::cartesian) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case LOOK_AT:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::origin = {operations[i + 1],
                               operations[i + 2],
                               operations[i + 3]};
                  cerr << "LOOK_AT(" << to_string (D::origin) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case UP:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::up = {operations[i + 1],
                           operations[i + 2],
                           operations[i + 3]};
                  cerr << "UP(" << to_string (D::up) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case PROJECTION:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::projection = {operations[i + 1],
                                   operations[i + 2],
                                   operations[i + 3]};
                  cerr << "PROJECTION(FOV: " << D::projection.x
                       << ", NEAR: " << D::projection.y
                       << ", FAR: " << D::projection.z
                       << ")" << endl;
                }
              i += 3;
            }
          continue;
          // transformations
          case ROTATE:
            {
              const float rotation_angle = operations[i + 1];
              const vec3 axis_of_rotation (operations[i + 2],
                                           operations[i + 3],
                                           operations[i + 4]);
              glRotatef (operations[i + 1],
                         operations[i + 2],
                         operations[i + 3],
                         operations[i + 4]);
              if (isFirstTimeBeingExecuted)
                cerr << "ROTATE (" << "rotation_angle:" << rotation_angle
                     << ", axis of rotatation: " << to_string (axis_of_rotation) << ")" << endl;
              i += 4; //angle, axis_of_rotation}
            }
          continue;
          case EXTENDED_ROTATE:
            {
              const float rotation_time = operations[i + 1];
              const vec3 axis_of_rotation = {
                  operations[i + 2],
                  operations[i + 3],
                  operations[i + 4]
              };
              advance_in_rotation (rotation_time, axis_of_rotation);
              i += 4; //time, axis_of_rotation
              if (isFirstTimeBeingExecuted)
                cerr << "EXTENDED_ROTATE (rotation_time: " << rotation_time
                     << " seconds, axis_of_rotation: " << to_string (axis_of_rotation) << ")" << endl;
            }
          continue;
          case TRANSLATE:
            {
              const vec3 translation (operations[i + 1],
                                      operations[i + 2],
                                      operations[i + 3]);
              glTranslatef (translation[0],
                            translation[1],
                            translation[2]);
              if (isFirstTimeBeingExecuted)
                cerr << "TRANSLATE (" << to_string (translation) << ")" << endl;
              i += 3;
            }
          continue;
          case EXTENDED_TRANSLATE:
            {
              const int number_of_points = (int) operations[i + 3];
              if (!hasLoadedCurves)
                {
                  vector<vec3> new_curve (number_of_points);
                  for (int j = 0; j < number_of_points; ++j)
                    {
                      const int idx = 3 * j;
                      new_curve.at (j)[0] = operations[i + 4 + idx];
                      new_curve.at (j)[1] = operations[i + 4 + idx + 1];
                      new_curve.at (j)[2] = operations[i + 4 + idx + 2];
                    }
                  curves.push_back (new_curve);
                }
              auto curve = curves.back ();
              renderCurve (Mcr, curve);
              const float translation_time = operations[i + 1];
              const bool align = (bool) operations[i + 2];
              advance_in_curve (translation_time, align, Mcr, curves.back ());
              if (isFirstTimeBeingExecuted)
                cerr << "EXTENDED_TRANSLATE ("
                     << "translation_time: " << translation_time
                     << ", align: " << align
                     << ", number of points: " << number_of_points
                     << ")" << endl;
              i += 3 + number_of_points * 3; // 3 - time,align,number_of_points,points...
            }
          continue;
          case SCALE:
            {
              const vec3 scale (operations[i + 1],
                                operations[i + 2],
                                operations[i + 3]);
              glScalef (scale[0],
                        scale[1],
                        scale[2]);
              if (isFirstTimeBeingExecuted)
                cerr << "SCALE (" << to_string (scale) << ")" << endl;
              i += 3;
            }
          continue;
          // grouping
          case BEGIN_GROUP:
            {
              if (isFirstTimeBeingExecuted)
                cerr << "BEGIN_GROUP" << endl;
              //glPushAttrib (GL_ALL_ATTRIB_BITS);
              glPushMatrix ();
            }
          continue;
          case END_GROUP:
            {
              if (isFirstTimeBeingExecuted)
                cerr << "END_GROUP" << endl;
              glPopMatrix ();
              //glPopAttrib ();
            }
          continue;
          // texture
          case TEXTURE:
            {
              const int stringSize = (int) operations[i + 1];
              if (!hasPushedModels)
                {
                  char textureFilePath[stringSize + 1];
                  int j;
                  for (j = 0; j < stringSize; ++j)
                    textureFilePath[j] = (char) operations[i + 2 + j];
                  textureFilePath[j] = '\0';
                  addTextureImageToModel (globalModels.back (), textureFilePath);
                  if (isFirstTimeBeingExecuted)
                    cerr << "TEXTURE (" << textureFilePath << ")" << endl;
                }
              i += stringSize + 1; //just to be explicit
            }
          continue;
          // object material components
          case DIFFUSE:
            {
              if (!hasPushedModels)
                {
                  auto &diffuse = globalModels.back ().material.diffuse;
                  diffuse[0] = operations[i + 1];
                  diffuse[1] = operations[i + 2];
                  diffuse[2] = operations[i + 3];
                  cerr << "DIFFUSE (" << to_string (diffuse) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case AMBIENT:
            {
              if (!hasPushedModels)
                {
                  auto &ambient = globalModels.back ().material.ambient;
                  ambient[0] = operations[i + 1];
                  ambient[1] = operations[i + 2];
                  ambient[2] = operations[i + 3];
                  cerr << "AMBIENT (" << to_string (ambient) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case SPECULAR:
            {
              if (!hasPushedModels)
                {
                  auto &specular = globalModels.back ().material.specular;
                  specular[0] = operations[i + 1];
                  specular[1] = operations[i + 2];
                  specular[2] = operations[i + 3];
                  cerr << "SPECULAR (" << to_string (specular) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case EMISSIVE:
            {
              if (!hasPushedModels)
                {
                  auto &emissive = globalModels.back ().material.emissive;
                  emissive[0] = operations[i + 1];
                  emissive[1] = operations[i + 2];
                  emissive[2] = operations[i + 3];
                  cerr << "EMISSIVE (" << to_string (emissive) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case SHININESS:
            {
              if (!hasPushedModels)
                {
                  float shininess = (globalModels.back ().material.shininess = operations[i + 1]);
                  cerr << "SHININESS (" << shininess << ")" << endl;
                }
              i += 1;
            }
          continue;
          // model
          case BEGIN_MODEL:
            {
              int stringSize = (int) operations[i + 1];
              if (!hasPushedModels)
                {
                  char modelName[stringSize + 1];
                  int j;
                  for (j = 0; j < stringSize; ++j)
                    modelName[j] = (char) operations[i + 2 + j];
                  modelName[j] = '\0';
                  globalModels.push_back (getModel (modelName));
                  if (isFirstTimeBeingExecuted)
                    cerr << "BEGIN_MODEL (" << modelName << ")" << endl;
                }
              ++model_num;
              i += stringSize + 1; //just to be explicit
            }
          continue;
          case END_MODEL:
            {
              if (isFirstTimeBeingExecuted)
                cerr << "END_MODEL" << endl;
              renderModel (globalModels[model_num - 1]);
            }
          continue;
          // light sources
          case POINT:
            {
              const vec4 pos = {operations[i + 1],
                                operations[i + 2],
                                operations[i + 3],
                                1.0};
              if (isFirstTimeBeingExecuted)
                {
                  glEnable (GL_LIGHT0 + nLights);
                  glLightfv (GL_LIGHT0 + nLights, GL_AMBIENT, amb);
                  glLightfv (GL_LIGHT0 + nLights, GL_DIFFUSE, diff);
                  glLightfv (GL_LIGHT0 + nLights, GL_SPECULAR, spec);
                  cerr << "POINT (" << to_string (pos) << ")" << endl;
                }
              glLightfv (GL_LIGHT0 + nLights, GL_POSITION, value_ptr (pos));
              ++nLights;
              i += 3;
            }
          continue;
          case DIRECTIONAL:
            {
              const vec4 dir = {operations[i + 1],
                                operations[i + 2],
                                operations[i + 3],
                                0.0};
              if (isFirstTimeBeingExecuted)
                {
                  glEnable (GL_LIGHT0 + nLights);
                  glLightfv (GL_LIGHT0 + nLights, GL_AMBIENT, amb);
                  glLightfv (GL_LIGHT0 + nLights, GL_DIFFUSE, diff);
                  glLightfv (GL_LIGHT0 + nLights, GL_SPECULAR, spec);
                  cerr << "DIRECTIONAL (" << to_string (dir) << ")" << endl;
                }
              glLightfv (GL_LIGHT0 + nLights, GL_POSITION, value_ptr (dir));
              ++nLights;
              i += 3;
            }
          continue;
          case SPOTLIGHT:
            {
              const vec4 pos = {operations[i + 1],
                                operations[i + 2],
                                operations[i + 3],
                                1.0};
              const vec4 dir = {operations[i + 4],
                                operations[i + 5],
                                operations[i + 6],
                                1.0};
              const float cutoff = operations[i + 7];
              if (isFirstTimeBeingExecuted)
                {
                  glEnable (GL_LIGHT0 + nLights);
                  glLightfv (GL_LIGHT0 + nLights, GL_AMBIENT, amb);
                  glLightfv (GL_LIGHT0 + nLights, GL_DIFFUSE, diff);
                  glLightfv (GL_LIGHT0 + nLights, GL_SPECULAR, spec);
                  glLightf (GL_LIGHT0 + nLights, GL_SPOT_CUTOFF, cutoff);
                  cerr << "SPOTLIGHT:"
                          "\n\t(pos: " << to_string (pos) << ")"
                                                             "\n\t(dir: " << to_string (dir) << ")"
                                                                                                "\n\t(cutoff: "
                       << cutoff
                       << ")" << endl;
                }
              glLightfv (GL_LIGHT0 + nLights, GL_POSITION, value_ptr (pos));
              glLightfv (GL_LIGHT0 + nLights, GL_SPOT_DIRECTION, value_ptr (dir));
              ++nLights;
              i += 7;
              continue;
            }
        }
    }
  // default mode uses explorer camera
  if (isFirstTimeBeingExecuted)
    cartesian2Spherical (D::origin, D::cartesian, D::polar);
  hasPushedModels = true;
  hasLoadedCurves = true;
  isFirstTimeBeingExecuted = false;
}
References addTextureImageToModel(), advance_in_curve(), advance_in_rotation(), model::ambient, AMBIENT, BEGIN_GROUP, BEGIN_MODEL, D::cartesian(), cartesian2Spherical(), model::diffuse, DIFFUSE, DIRECTIONAL, model::emissive, EMISSIVE, END_GROUP, END_MODEL, EXTENDED_ROTATE, EXTENDED_TRANSLATE, getModel(), globalModels, LOOK_AT, Mcr, D::origin(), POINT, D::polar(), POSITION, D::projection(), PROJECTION, renderCurve(), renderModel(), ROTATE, D::scale(), SCALE, model::shininess, SHININESS, model::specular, SPECULAR, SPOTLIGHT, TEXTURE, TRANSLATE, D::up(), and UP.
Referenced by renderScene(), and xml_load_and_set_env().