Solar System - demo scence: Transforms
Transforms
Operations
Functions
void operations_push_transform_attributes (const XMLElement *const transform, vector< float > &operations)
void operations_push_extended_translate_attributes (const XMLElement *const extended_translate, vector< float > &operations)
void operations_push_transformation (const XMLElement *const transformation, vector< float > &operations)
void operations_push_transforms (const XMLElement *const transforms, vector< float > &operations)
Detailed Description
Function Documentation
operations_push_extended_translate_attributes()
void operations_push_extended_translate_attributes (const XMLElement *const extended_translate, vector< float > & operations)
Definition at line 106 of file parsing.cpp.
{
  if (!extended_translate)
    {
      fprintf (stderr, "[parsing] Null transform\n");
      exit (EXIT_FAILURE);
    }
  float time;
  if (extended_translate->QueryFloatAttribute ("time", &time))
    {
      cerr << "[parsing] failed parsing time" << endl;
      exit (EXIT_FAILURE);
    }
  bool align;
  if (extended_translate->QueryBoolAttribute ("align", &align))
    {
      cerr << "[parsing] failed parsing align" << endl;
      exit (EXIT_FAILURE);
    }
  operations.push_back ((float) time);
  operations.push_back ((float) align);
  operations.push_back (0); // create space to insert the number of points
  auto index_of_number_of_points = operations.size () - 1;
  int number_of_points = 0;
  for (auto child = extended_translate->FirstChildElement ("point"); child; child = child->NextSiblingElement ("point"))
    {
      ++number_of_points;
      operations_push_transform_attributes (child, operations);
    }
  operations[index_of_number_of_points] = (float) number_of_points;
}
References operations_push_transform_attributes().
Referenced by operations_push_transformation().
operations_push_transform_attributes()
void operations_push_transform_attributes (const XMLElement *const transform, vector< float > & operations)
Definition at line 70 of file parsing.cpp.
{
  if (!transform)
    {
      fprintf (stderr, "[parsing] operations_push_transform_attributes: null transform\n");
      exit (EXIT_FAILURE);
    }
  float angle;
  {
    const XMLError e = transform->QueryFloatAttribute ("angle", &angle);
    if (e == XML_SUCCESS)
      operations.push_back (angle);
    else if (e != XML_NO_ATTRIBUTE)
      {
        fprintf (stderr, "[parsing] Parsing error %s at %s\n", transform->GetText (), XMLDocument::ErrorIDToName (e));
        exit (EXIT_FAILURE);
      }
  }
  for (const char *const attribute_name : {"x", "y", "z"})
    {
      float attributeValue;
      XMLError e;
      if ((e = transform->QueryFloatAttribute (attribute_name, &attributeValue)) != XML_SUCCESS)
        {
          fprintf (stderr, "[parsing] Parsing error %s at %s\n", transform->GetText (), XMLDocument::ErrorIDToName (e));
          exit (EXIT_FAILURE);
        }
      operations.push_back (attributeValue);
    }
}
Referenced by operations_load_xml(), operations_push_extended_translate_attributes(), and operations_push_transformation().
operations_push_transformation()
void operations_push_transformation (const XMLElement *const transformation, vector< float > & operations)
Definition at line 143 of file parsing.cpp.
{
  assert (transformation != nullptr);
  const char *const transformation_name = transformation->Value ();
  if (!strcmp ("translate", transformation_name))
    {
      if (transformation->Attribute ("time") != nullptr)
        {
          operations.push_back (EXTENDED_TRANSLATE);
          cerr << "[parsing] EXTENDED_TRANSLATE" << endl;
          operations_push_extended_translate_attributes (transformation, operations);
        }
      else
        {
          operations.push_back (TRANSLATE);
          cerr << "[parsing] TRANSLATE" << endl;
          operations_push_transform_attributes (transformation, operations);
        }
    }
  else if (!strcmp ("rotate", transformation_name))
    {
      if (transformation->Attribute ("time"))
        {
          operations.push_back (EXTENDED_ROTATE);
          cerr << "[parsing] EXTENDED_ROTATE" << endl;
          float time;
          if (transformation->QueryFloatAttribute ("time", &time))
            {
              cerr << "[parsing] failed parsing time" << endl;
              exit (EXIT_FAILURE);
            }
          operations.push_back (time);
          operations_push_transform_attributes (transformation, operations);
        }
      else
        {
          operations.push_back (ROTATE);
          cerr << "[parsing] ROTATE" << endl;
          operations_push_transform_attributes (transformation, operations);
        }
    }
  else if (!strcmp ("scale", transformation_name))
    {
      operations.push_back (SCALE);
      cerr << "[parsing] SCALE" << endl;
      operations_push_transform_attributes (transformation, operations);
    }
  else
    {
      fprintf (stderr, "[parsing] Unknown transformation: \"%s\"", transformation_name);
      exit (EXIT_FAILURE);
    }
}
References EXTENDED_ROTATE, EXTENDED_TRANSLATE, operations_push_extended_translate_attributes(), operations_push_transform_attributes(), ROTATE, SCALE, and TRANSLATE.
Referenced by operations_push_transforms().
operations_push_transforms()
void operations_push_transforms (const XMLElement *const transforms, vector< float > & operations)
Definition at line 199 of file parsing.cpp.
{
  const XMLElement *transform = transforms->FirstChildElement ();
  do
    operations_push_transformation (transform, operations);
  while ((transform = transform->NextSiblingElement ()));
}
References operations_push_transformation().
Referenced by operations_push_groups().