Solar System - demo scence: Parsing
Parsing
Operations
Modules
Auxiliary
Functions
void operations_push_any (const XMLElement *element, vector< float > &operations)
void operations_load_xml (const string &filename, vector< float > &operations)
Detailed Description
Function Documentation
operations_load_xml()
void operations_load_xml (const string & filename, vector< float > & operations)
Definition at line 361 of file parsing.cpp.
{
  XMLDocument doc;
  if (doc.LoadFile (filename.c_str ()))
    {
      cerr << "[parsing] Failed loading file: '" << filename << "'"
           << "\n\tERROR: " << doc.ErrorName () << endl;
      exit (EXIT_FAILURE);
    }
  cerr << "[parsing] Loaded file: '" << filename << "'" << endl;
  const XMLElement *const world = doc.FirstChildElement ("world");
  operations_push_any (world, operations);
}
References operations_push_any().
Referenced by xml_load_and_set_env().
operations_push_any()
void operations_push_any (const XMLElement * element, vector< float > & operations)
Definition at line 190 of file parsing.cpp.
{
  static string generatorExecutable;
  static bool isUsingGenerator = false;
  do
    {
      auto elementEnum = elementToEnum (element->Value ());
      switch (elementEnum)
        {
          case GROUP:
            {
              switch (element->ClosingType ())
                {
                  case XMLElement::OPEN:
                    operations.push_back (BEGIN_GROUP);
                  break;
                  case XMLElement::CLOSED:
                    break;
                  case XMLElement::CLOSING:
                    operations.push_back (END_GROUP); //never happens...i think
                  break;
                }
              break;
            }
          case GENERATOR:
            {
              if (element->Attribute ("dir"))
                {
                  generatorExecutable = getAttribute<string> (*element, "dir");
                  crashIfFileDoesNotExist (generatorExecutable);
                  cerr << "[parsing] using generator " << generatorExecutable << endl;
                  isUsingGenerator = true;
                }
              else if (isUsingGenerator)
                {
                  auto generator_argv = getAttribute<string> (*element, "argv");
                  std::stringstream command;
                  command << std::filesystem::current_path ()
                          << "/" << generatorExecutable << " " << generator_argv;
                  if (system (command.str ().data ()))
                    {
                      cerr << "[parsing] generator failed at line " << element->GetLineNum () << endl;
                      exit (EXIT_FAILURE);
                    }
                }
              break;
            }
          case MODEL:
            {
              switch (element->ClosingType ())
                {
                  case XMLElement::OPEN:
                    operations.push_back (BEGIN_MODEL);
                  case XMLElement::CLOSED:
                    operations_push_string_attribute (*element, operations, "file");
                  break;
                  case XMLElement::CLOSING: // never happens...i think
                    operations.push_back (END_MODEL);
                  break;
                }
              break;
            }
          case ROTATE:
            {
              if (element->Attribute ("time"))
                operations.push_back (EXTENDED_ROTATE);
              else
                operations.push_back (ROTATE);
              pushFloatAttributes (*element, operations);
              break;
            }
          case TRANSLATE:
            {
              switch (element->ClosingType ())
                {
                  // ⟨extended_translation⟩ ::= ⟨EXTENDED_TRANSLATE⟩⟨time⟩⟨align⟩⟨number_of_points⟩⟨vec3f⟩⁺
                  case XMLElement::OPEN:
                    {
                      operations.push_back (EXTENDED_TRANSLATE);
                      auto time = getAttribute<float> (*element, "time");
                      auto align = getAttribute<bool> (*element, "align");
                      operations.insert (operations.end (), {time, (float) align});
                      operations.push_back (0); // create space to insert the number of points
                      auto index_of_number_of_points = operations.size () - 1;
                      auto number_of_points = 0;
                      for (auto child = element->FirstChildElement ("point"); child;
                           child = child->NextSiblingElement ("point"))
{
                          ++number_of_points;
                          pushFloatAttributes (*child, operations);
                        }
                      operations[index_of_number_of_points] = (float) number_of_points;
                    }
                  break;
                  // ⟨simple_translation⟩ ::= ⟨TRANSLATE⟩⟨vec3f⟩
                  case XMLElement::CLOSED:
                    {
                      operations.push_back (TRANSLATE);
                      pushFloatAttributes (*element, operations);
                    }
                  break;
                  case XMLElement::CLOSING:
                    break;
                }
              break;
            }
          case TEXTURE:     // ⟨texture⟩ ::= ⟨TEXTURE⟩ ⟨number of characters⟩ ⟨char⟩⁺
            {
              operations.push_back (elementEnum);
              operations_push_string_attribute (*element, operations, "file");
              break;
            }
          // (⟨DIFFUSE⟩ | ⟨AMBIENT⟩ | ⟨SPECULAR⟩ | ⟨EMISSIVE⟩) ⟨nvec3f⟩
          case DIFFUSE:
          case AMBIENT:
          case SPECULAR:
          case EMISSIVE:
            {
              operations.push_back (elementEnum);
              const float RGB_MAX = 255.0f;
              auto R = getAttribute<float> (*element, "R");
              auto G = getAttribute<float> (*element, "G");
              auto B = getAttribute<float> (*element, "B");
              assert (R >= 0 && G >= 0 && B >= 0);
              assert (R <= RGB_MAX && G <= RGB_MAX && B <= RGB_MAX);
              operations.insert (operations.end (), {R / RGB_MAX, G / RGB_MAX, B / RGB_MAX});
              break;
            }
          case LIGHT: // ⟨point⟩ | ⟨directional⟩ | ⟨spotlight⟩
            {
              elementEnum = elementToEnum (getAttribute<string> (*element, "type"));
              if (elementEnum == OTHER)
                elementEnum = POINT;
            }
          case SHININESS:           // SHININESS⟩ ⟨float ∈ [0, 128]⟩
          case SCALE:               // ⟨scaling⟩ ::= ⟨SCALE⟩⟨vec3f⟩
          case POINT:               // ⟨point⟩        ::= ⟨POINT⟩⟨vec3f⟩
          case DIRECTIONAL:         // ⟨directional⟩  ::= ⟨DIRECTIONAL⟩⟨vec3f⟩
          case SPOTLIGHT:           // ⟨spotlight⟩    ::= ⟨SPOTLIGHT⟩⟨vec3f⟩⟨vec3f⟩⟨cutoff⟩
          case POSITION:            // ⟨position⟩   ::= ⟨POSITION⟩ ⟨vec3f⟩
          case LOOK_AT:             // ⟨lookAt⟩     ::= ⟨LOOK_AT⟩ ⟨vec3f⟩
          case UP:                  // ⟨up⟩         ::= ⟨UP⟩ ⟨vec3f⟩
          case PROJECTION:          // ⟨projection⟩ ::= ⟨PROJECTION⟩ ⟨vec3f⟩
            {
              operations.push_back (elementEnum);
              pushFloatAttributes (*element, operations);
            }
          break;
        }
      auto child = element->FirstChildElement ();
      if (child != nullptr)
        operations_push_any (child, operations);
      switch (elementEnum)
        {
          case MODEL:
            if (element->ClosingType () == tinyxml2::XMLElement::OPEN)
              operations.push_back (END_MODEL);
          break;
          case GROUP:
            operations.push_back (END_GROUP);
          break;
        }
    }
  while ((element = element->NextSiblingElement ()) != nullptr);
}
References AMBIENT, BEGIN_GROUP, BEGIN_MODEL, crashIfFileDoesNotExist(), DIFFUSE, DIRECTIONAL, elementToEnum(), EMISSIVE, END_GROUP, END_MODEL, EXTENDED_ROTATE, EXTENDED_TRANSLATE, GENERATOR, GROUP, LIGHT, LOOK_AT, MODEL, operations_push_any(), operations_push_string_attribute(), OTHER, POINT, POSITION, PROJECTION, pushFloatAttributes(), RGB_MAX, ROTATE, SCALE, SHININESS, SPECULAR, SPOTLIGHT, TEXTURE, TRANSLATE, and UP.
Referenced by operations_load_xml(), and operations_push_any().