Solar System Project: Model
Model
Modules
Generator
Functions
int main (int argc, char *argv[])
Detailed Description
Function Documentation
main()
int main (int argc, char * argv[])
{
    if (argc < 5) { printf("Not enough arguments"); }
    else {
        const char *filepath = argv[argc - 1];
        const char *polygon = argv[1];
        if (!strcmp(PLANE, polygon))
            model_plane_write(filepath, strtof(argv[2], nullptr), strtoul(argv[3], nullptr, 10));
        if (!strcmp(CUBE, polygon)) model_cube_write(filepath, atof(argv[2]), strtoul(argv[3], nullptr, 10));
        if (!strcmp(CONE, polygon))
            model_cone_write(filepath, atof(argv[2]), atof(argv[3]), atoi(argv[4]), atoi(argv[5]));
        if (!strcmp(SPHERE, polygon)) model_sphere_write(filepath, atof(argv[2]), atoi(argv[3]), atoi(argv[4]));
    }
    return 1;
}
References CONE, CUBE, model_cone_write(), model_cube_write(), model_plane_write(), model_sphere_write(), PLANE, and SPHERE.