Solar System - demo scence: Cube
Cube
Generator » Model
Functions
void model_cube_vertices (const float length, const unsigned int divisions, vector< vec3 > &vertices, vector< vec3 > &normals, vector< vec2 > &texture)
static unsigned int model_cube_nVertices (const unsigned int divisions)
void model_cube_write (const char *const filepath, const float length, const unsigned int divisions)
Detailed Description
Function Documentation
model_cube_nVertices()
static unsigned int model_cube_nVertices (const unsigned int divisions) inline static
Definition at line 329 of file generator.cpp.
{ return divisions * divisions * 36; }
Referenced by model_cube_write().
model_cube_vertices()
void model_cube_vertices (const float length, const unsigned int divisions, vector< vec3 > & vertices, vector< vec3 > & normals, vector< vec2 > & texture)
Definition at line 177 of file generator.cpp.
{
  const float o = -length / 2.0f;
  const float d = length / (float) divisions;
  for (unsigned int uidiv1 = 1; uidiv1 <= divisions; uidiv1++)
    {
      for (unsigned int uidiv2 = 1; uidiv2 <= divisions; uidiv2++)
        {
          auto const fdiv1 = (float) uidiv1;
          auto const fdiv2 = (float) uidiv2;
          auto const fdivisions = (float) divisions;
          // y+
          for (auto e : {
              array<float, 2>{-1, -1}, //P1
              array<float, 2>{-1, 0}, //P1'z
              array<float, 2>{0, -1}, //P1'x
              array<float, 2>{0, -1}, //P1'x
              array<float, 2>{-1, 0}, //P1'z
              array<float, 2>{0, 0}   //P2
          })
            {
              vertices.emplace_back (o + d * (fdiv1 + e[0]), -o, o + d * (fdiv2 + e[1]));
              normals.emplace_back (0, 1, 0);
              texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
            }
          // y-
          vertices.emplace_back (o + d * (fdiv1 - 1), o, o + d * fdiv2); //P1'z
          vertices.emplace_back (o + d * (fdiv1 - 1), o, o + d * (fdiv2 - 1)); //P1
          vertices.emplace_back (o + d * fdiv1, o, o + d * (fdiv2 - 1)); //P1'x
          vertices.emplace_back (o + d * (fdiv1 - 1), o, o + d * fdiv2); //P1'z
          vertices.emplace_back (o + d * fdiv1, o, o + d * (fdiv2 - 1)); //P1'x
          vertices.emplace_back (o + d * fdiv1, o, o + d * fdiv2); //P2
          for (int k = 0; k < 6; ++k)
            normals.emplace_back (0, -1, 0);
          for (auto e : {
              vec2 (-1.0f, 0.0f),
              vec2 (-1.0f, -1.0f),
              vec2 (0.0f, -1.0f),
              vec2 (-1.0f, 0.0f),
              vec2 (0.0f, -1.0f),
              vec2 (0.0f, 0.0f)})
            texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
          // x-
          vertices.emplace_back (o, o + d * (fdiv1 - 1), o + d * (fdiv2 - 1)); //P1
          vertices.emplace_back (o, o + d * (fdiv1 - 1), o + d * fdiv2); //P1'z
          vertices.emplace_back (o, o + d * fdiv1, o + d * (fdiv2 - 1)); //P1'x
          vertices.emplace_back (o, o + d * fdiv1, o + d * (fdiv2 - 1)); //P1'x
          vertices.emplace_back (o, o + d * (fdiv1 - 1), o + d * fdiv2); //P1'z
          vertices.emplace_back (o, o + d * fdiv1, o + d * fdiv2); //P2
          for (int k = 0; k < 6; ++k)
            normals.emplace_back (-1, 0, 0);
          for (auto e : {
              vec2 (-1.0f, -1.0f),
              vec2 (-1.0f, 0.0f),
              vec2 (0.0f, -1.0f),
              vec2 (0.0f, -1.0f),
              vec2 (-1.0f, 0.0f),
              vec2 (0.0f, 0.0f)})
            texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
          // x+
          vertices.emplace_back (-o, o + d * (fdiv1 - 1), o + d * fdiv2); //P1'z
          vertices.emplace_back (-o, o + d * (fdiv1 - 1), o + d * (fdiv2 - 1)); //P1
          vertices.emplace_back (-o, o + d * fdiv1, o + d * (fdiv2 - 1)); //P1'x
          vertices.emplace_back (-o, o + d * (fdiv1 - 1), o + d * fdiv2); //P1'z
          vertices.emplace_back (-o, o + d * fdiv1, o + d * (fdiv2 - 1)); //P1'x
          vertices.emplace_back (-o, o + d * fdiv1, o + d * fdiv2); //P2
          for (int k = 0; k < 6; ++k)
            normals.emplace_back (1, 0, 0);
          for (auto e : {
              vec2 (-1.0f, 0.0f),
              vec2 (-1.0f, -1.0f),
              vec2 (0.0f, -1.0f),
              vec2 (-1.0f, 0.0f),
              vec2 (0.0f, -1.0f),
              vec2 (0.0f, 0.0f)})
            texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
          // z-
          vertices.emplace_back (o + d * (fdiv1 - 1), o + d * (fdiv2 - 1), o); //P1
          vertices.emplace_back (o + d * (fdiv1 - 1), o + d * fdiv2, o); //P1'z
          vertices.emplace_back (o + d * fdiv1, o + d * (fdiv2 - 1), o); //P1'x
          vertices.emplace_back (o + d * fdiv1, o + d * (fdiv2 - 1), o); //P1'x
          vertices.emplace_back (o + d * (fdiv1 - 1), o + d * fdiv2, o); //P1'z
          vertices.emplace_back (o + d * fdiv1, o + d * fdiv2, o); //P2
          for (auto e : {
              vec2 (-1.0f, -1.0f),//P1
              vec2 (-1.0f, 0.0f),//P1'z
              vec2 (0.0f, -1.0f),//P1'x
              vec2 (0.0f, -1.0f),//P1'x
              vec2 (-1.0f, 0.0f),//P1'z
              vec2 (0.0f, 0.0f)//P2
          })
            {
              normals.emplace_back (0, 0, -1);
              texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
            }
          // z+
          vertices.emplace_back (o + d * (fdiv1 - 1), o + d * fdiv2, -o); //P1'z
          vertices.emplace_back (o + d * (fdiv1 - 1), o + d * (fdiv2 - 1), -o); //P1
          vertices.emplace_back (o + d * fdiv1, o + d * (fdiv2 - 1), -o); //P1'x
          vertices.emplace_back (o + d * (fdiv1 - 1), o + d * fdiv2, -o); //P1'z
          vertices.emplace_back (o + d * fdiv1, o + d * (fdiv2 - 1), -o); //P1'x
          vertices.emplace_back (o + d * fdiv1, o + d * fdiv2, -o); //P2
          for (int k = 0; k < 6; ++k)
            normals.emplace_back (0, 0, 1);
          for (auto e : {
              vec2 (-1.0f, 0.0f),
              vec2 (-1.0f, -1.0f),
              vec2 (0.0f, -1.0f),
              vec2 (-1.0f, 0.0f),
              vec2 (0.0f, -1.0f),
              vec2 (0.0f, 0.0f)
          })
            texture.emplace_back ((fdiv1 + e[0]) / fdivisions, (fdiv2 + e[1]) / fdivisions);
        }
    }
}
Referenced by model_cube_write().
model_cube_write()
void model_cube_write (const char *const filepath, const float length, const unsigned int divisions)
Definition at line 332 of file generator.cpp.
{
  const unsigned int nVertices = model_cube_nVertices (divisions);
  vector<vec3> vertices;
  vertices.reserve (nVertices);
  vector<vec3> normals;
  normals.reserve (nVertices);
  vector<vec2> texture;
  texture.reserve (nVertices);
  model_cube_vertices (length, divisions, vertices, normals, texture);
  model_write (filepath, vertices, normals, texture);
}
References model_cube_nVertices(), model_cube_vertices(), and model_write().
Referenced by main().