Solar System - demo scence: Auxiliary
Auxiliary
Operations » Parsing
Functions
void crashIfFileDoesNotExist (const string &filename, const string &additional_info="")
void crashIfFailedAttributeQuery (const XMLError error, const XMLElement &element, const string &attributeName)
template<typename T >
T getAttribute (const XMLElement &e, const string &attributeName)
int operations_push_string_attribute (const XMLElement &element, vector< float > &operations, string &&attribute_name)
int elementToEnum (string &&s)
void pushFloatAttributes (const XMLElement &element, vector< float > &operations)
Detailed Description
Function Documentation
crashIfFailedAttributeQuery()
void crashIfFailedAttributeQuery (const XMLError error, const XMLElement & element, const string & attributeName)
Definition at line 91 of file parsing.cpp.
{
  if (!error)
    return;
  cerr << "[parsing] failed parsing attribute " << attributeName << " of element " << element.Value ()
       << "\nError: " << XMLDocument::ErrorIDToName (error) << endl;
  exit (EXIT_FAILURE);
}
Referenced by getAttribute().
crashIfFileDoesNotExist()
void crashIfFileDoesNotExist (const string & filename, const string & additional_info = "")
Definition at line 83 of file parsing.cpp.
{
  if (exists (filename))
    return;
  cerr << "[parsing] Failed loading " << filename << " " << additional_info << endl;
  exit (EXIT_FAILURE);
}
Referenced by operations_push_any().
elementToEnum()
int elementToEnum (string && s)
Definition at line 145 of file parsing.cpp.
{
  map<string, int> m{
      {"translate", TRANSLATE},
      {"rotate", ROTATE},
      {"scale", SCALE},
      {"model", MODEL},
      {"texture", TEXTURE},
      {"diffuse", DIFFUSE},
      {"ambient", AMBIENT},
      {"specular", SPECULAR},
      {"emissive", EMISSIVE},
      {"shininess", SHININESS},
      //{"point", POINT}, //conflicts with point in extended translate
      {"directional", DIRECTIONAL},
      {"spotlight", SPOTLIGHT},
      {"position", POSITION},
      {"lookAt", LOOK_AT},
      {"up", UP},
      {"projection", PROJECTION},
      {"group", GROUP},
      {"generator", GENERATOR},
      {"light", LIGHT}
  };
  if (m.count (s))
    return m[s];
  else
    return OTHER;
}
References AMBIENT, DIFFUSE, DIRECTIONAL, EMISSIVE, GENERATOR, GROUP, LIGHT, LOOK_AT, MODEL, OTHER, POSITION, PROJECTION, ROTATE, SCALE, SHININESS, SPECULAR, SPOTLIGHT, TEXTURE, TRANSLATE, and UP.
Referenced by operations_push_any().
getAttribute()
template<typename T > T getAttribute (const XMLElement & e, const string & attributeName)
Definition at line 101 of file parsing.cpp.
{
  T _attributeValue;
  XMLError error;
  if constexpr(std::is_same<string, T>::value)
    {
      const char **attributeValue;
      error = e.QueryStringAttribute (attributeName.c_str (), attributeValue);
      _attributeValue = string{*attributeValue};
    }
  else if constexpr(std::is_same<float, T>::value)
    {
      float attributeValue;
      error = e.QueryFloatAttribute (attributeName.c_str (), &attributeValue);
      _attributeValue = attributeValue;
    }
  else if constexpr(std::is_same<bool, T>::value)
    {
      bool attributeValue;
      error = e.QueryBoolAttribute (attributeName.c_str (), &attributeValue);
      _attributeValue = attributeValue;
    }
  crashIfFailedAttributeQuery (error, e, attributeName);
  return _attributeValue;
}
References crashIfFailedAttributeQuery().
operations_push_string_attribute()
int operations_push_string_attribute (const XMLElement & element, vector< float > & operations, string && attribute_name)
Definition at line 129 of file parsing.cpp.
{
  auto element_attribute_value = getAttribute<string> (element, attribute_name);
  int i = 0;
  do
    operations.push_back (element_attribute_value[i++]);
  while (element_attribute_value[i]);
  // add number of characters of element attribute string value
  operations.insert (operations.end () - i, (float) i);
  return i;
}
Referenced by operations_push_any().
pushFloatAttributes()
void pushFloatAttributes (const XMLElement & element, vector< float > & operations)
Definition at line 175 of file parsing.cpp.
{
  auto attribute = element.FirstAttribute ();
  if (attribute != nullptr)
    do
      {
        float attributeValue;
        if (attribute->QueryFloatValue (&attributeValue) == XML_SUCCESS)
          operations.push_back (attribute->FloatValue ());
      }
    while ((attribute = attribute->Next ()) != nullptr);
}
Referenced by operations_push_any().