Solar System - demo scence: Xml
Xml
Operations
Functions
void operations_push_lights (const XMLElement *const lights, vector< float > &operations)
void operations_load_xml (const char *const filename, vector< float > &operations)
Detailed Description
Function Documentation
operations_load_xml()
void operations_load_xml (const char *const filename, vector< float > & operations)
Definition at line 480 of file parsing.cpp.
{
  XMLDocument doc;
  if (doc.LoadFile (filename))
    {
      if (doc.ErrorID () == tinyxml2::XML_ERROR_FILE_NOT_FOUND)
        fprintf (stderr, "[parsing] Failed loading file: '%s'\n", filename);
      fprintf (stderr, "%s", doc.ErrorName ());
      exit (EXIT_FAILURE);
    }
  fprintf (stderr, "[parsing] Loaded file: '%s'\n", filename);
  const XMLElement *const world = doc.FirstChildElement ("world");
  /*camera*/
  const XMLElement *const camera = world->FirstChildElement ("camera");
  const XMLElement *const position = camera->FirstChildElement ("position");
  operations_push_transform_attributes (position, operations);
  const XMLElement *const lookAt = camera->FirstChildElement ("lookAt");
  operations_push_transform_attributes (lookAt, operations);
  const XMLElement *const up = camera->FirstChildElement ("up");
  if (up)
    operations_push_transform_attributes (up, operations);
  else
    operations.insert (operations.end (), {0, 1, 0});
  const XMLElement *const projection = camera->FirstChildElement ("projection");
  if (projection)
    {
      float fov;
      if (projection->QueryFloatAttribute ("fov", &fov))
        {
          cerr << "[parsing] Failed parsing fov" << endl;
          exit (EXIT_FAILURE);
        }
      float near;
      if (projection->QueryFloatAttribute ("near", &near))
        {
          cerr << "[parsing] Failed parsing near" << endl;
          exit (EXIT_FAILURE);
        }
      float far;
      if (projection->QueryFloatAttribute ("far", &far))
        {
          cerr << "[parsing] Failed parsing far" << endl;
          exit (EXIT_FAILURE);
        }
      operations.insert (operations.end (), {fov, near, far});
    }
  else
    operations.insert (operations.end (), {60, 1, 1000});
  /*end of camera*/
  // lights
  const XMLElement *const lights = world->FirstChildElement ("lights");
  if (lights != nullptr)
    operations_push_lights (lights, operations);
  // find generator if it exists
  const XMLElement *const generator = world->FirstChildElement ("generator");
  if (generator != nullptr)
    {
      const char **generator_executable;
      if (generator->QueryStringAttribute ("dir", generator_executable))
        {
          cerr << "[parsing] failed parsing attribute dir of generator" << endl;
          exit (EXIT_FAILURE);
        }
      if (access (*generator_executable, F_OK))
        {
          cerr << "[parsing] generator " << *generator_executable << " not found" << endl;
          exit (EXIT_FAILURE);
        }
      cerr << "[parsing] using generator " << *generator_executable << endl;
      strncpy (globalGeneratorExecutable, *generator_executable, BUFSIZ);
      globalUsingGenerator = true;
    }
  // groups
  const XMLElement *const group = world->FirstChildElement ("group");
  operations_push_groups (group, operations);
}
References globalGeneratorExecutable, globalUsingGenerator, operations_push_groups(), operations_push_lights(), and operations_push_transform_attributes().
Referenced by xml_load_and_set_env().
operations_push_lights()
void operations_push_lights (const XMLElement *const lights, vector< float > & operations)
Definition at line 401 of file parsing.cpp.
{
  const XMLElement *light = lights->FirstChildElement ();
  do
    {
      const char *lightType[2];
      if (light->QueryStringAttribute ("type", lightType))
        {
          cerr << "failed parsing type attribute of light" << endl;
          exit (EXIT_FAILURE);
        }
      if (!strcmp (*lightType, "point"))
        {
          operations.push_back (POINT);
          float posX, posY, posZ;
          if (light->QueryFloatAttribute ("posX", &posX)
              | light->QueryFloatAttribute ("posY", &posY)
              | light->QueryFloatAttribute ("posZ", &posZ))
            {
              cerr << "[parsing] Failed parsing POINT posX or posY or posZ" << endl;
              exit (EXIT_FAILURE);
            }
          operations.insert (operations.end (), {posX, posY, posZ});
        }
      else if (!strcmp (*lightType, "directional"))
        {
          operations.push_back (DIRECTIONAL);
          float dirX, dirY, dirZ;
          if (light->QueryFloatAttribute ("dirX", &dirX)
              | light->QueryFloatAttribute ("dirY", &dirY)
              | light->QueryFloatAttribute ("dirZ", &dirZ))
            {
              cerr << "[parsing] Failed parsing DIRECTIONAL dirX or dirY or dirZ" << endl;
              exit (EXIT_FAILURE);
            }
          operations.insert (operations.end (), {dirX, dirY, dirZ});
        }
      else if (!strcmp (*lightType, "spotlight"))
        {
          operations.push_back (SPOTLIGHT);
          float posX, posY, posZ;
          if (light->QueryFloatAttribute ("posX", &posX)
              | light->QueryFloatAttribute ("posY", &posY)
              | light->QueryFloatAttribute ("posZ", &posZ))
            {
              cerr << "[parsing] Failed parsing SPOTLIGHT posX or posY or posZ" << endl;
              exit (EXIT_FAILURE);
            }
          float dirX, dirY, dirZ;
          if (light->QueryFloatAttribute ("dirX", &dirX)
              | light->QueryFloatAttribute ("dirY", &dirY)
              | light->QueryFloatAttribute ("dirZ", &dirZ))
            {
              cerr << "[parsing] Failed parsing SPOTLIGHT dirX or dirY or dirZ" << endl;
              exit (EXIT_FAILURE);
            }
          float cutoff;
          if (light->QueryFloatAttribute ("cutoff", &cutoff))
            {
              cerr << "[parsing] Failed parsing SPOTLIGHT cutoff" << endl;
              exit (EXIT_FAILURE);
            }
          operations.insert (operations.end (), {
              posX, posY, posZ,
              dirX, dirY, dirZ,
              cutoff
          });
        }
      else
        {
          fprintf (stderr, "[parsing] Unkown light type: %s\n", lightType);
          exit (EXIT_FAILURE);
        }
    }
  while ((light = light->NextSiblingElement ()));
}
References DIRECTIONAL, POINT, and SPOTLIGHT.
Referenced by operations_load_xml().