Solar System - demo scence: CLI
CLI
Generator
Functions
int main (const int argc, const char *const argv[])
Detailed Description
Function Documentation
main()
int main (const int argc, const char *const argv[])
⟨command⟩ ::= (⟨plane⟩ | ⟨cube⟩ | ⟨sphere⟩ | ⟨cone⟩ | ⟨patch⟩) ⟨out_file⟩
⟨patch⟩   ::= "bezier" ⟨patch_file⟩ ⟨tesselation⟩
⟨plane⟩   ::= "plane" ⟨length⟩ ⟨divisions⟩
⟨cube⟩    ::= "box" ⟨length⟩ ⟨divisions⟩
⟨cone⟩    ::= "cone" ⟨base_radius⟩ ⟨height⟩ ⟨slices⟩ ⟨stacks⟩
⟨sphere⟩  ::= "sphere" ⟨radius⟩ ⟨slices⟩ ⟨stacks⟩
Definition at line 796 of file generator.cpp.
{
  if (argc < 4)
    {
      cerr << "[generator] Not enough arguments" << endl;
      exit (EXIT_FAILURE);
    }
  else
    {
      const char *const out_file_path = argv[argc - 1];
      cerr << "[generator] output filepath: '" << out_file_path << "'" << endl;
      const char *const polygon = argv[1];
      cerr << "[generator] polygon to generate: " << polygon << endl;
      const char *SPHERE = "sphere";
      const char *CUBE = "box";
      const char *CONE = "cone";
      const char *PLANE = "plane";
      const char *BEZIER = "bezier";
      if (!strcmp (PLANE, polygon))
        {
          const float length = strtof (argv[2], nullptr);
          if (length <= 0.0)
            {
              cerr << "[generator] invalid length(" << length << ") for plane" << endl;
              exit (EXIT_FAILURE);
            }
          const int divisions = std::stoi (argv[3], nullptr, 10);
          if (divisions <= 0)
            {
              cerr << "[generator] invalid number of divisions(" << divisions << ") for plane" << endl;
              exit (EXIT_FAILURE);
            }
          cerr << "[generator] PLANE(length: " << length << ", divisions: " << divisions << ")" << endl;
          model_plane_write (out_file_path, length, divisions);
        }
      else if (!strcmp (CUBE, polygon))
        {
          const float length = strtof (argv[2], nullptr);
          if (length <= 0.0)
            {
              cerr << "[generator] invalid length(" << length << ") for cube" << endl;
              exit (EXIT_FAILURE);
            }
          const int divisions = std::stoi (argv[3], nullptr, 10);
          if (divisions <= 0)
            {
              cerr << "[generator] invalid number of divisions(" << divisions << ") for cube" << endl;
              exit (EXIT_FAILURE);
            }
          cerr << "[generator] CUBE(length: " << length << ", divisions: " << divisions << ")" << endl;
          model_cube_write (out_file_path, length, divisions);
        }
      else if (!strcmp (CONE, polygon))
        {
          const float radius = strtof (argv[2], nullptr);
          if (radius <= 0.0)
            {
              cerr << "[generator] invalid radius(" << radius << ") for cone" << endl;
              exit (EXIT_FAILURE);
            }
          const float height = strtof (argv[3], nullptr);
          if (height <= 0.0)
            {
              cerr << "[generator] invalid height(" << radius << ") for cone" << endl;
              exit (EXIT_FAILURE);
            }
          const int slices = std::stoi (argv[4], nullptr, 10);
          if (slices <= 0)
            {
              cerr << "[generator] invalid slices(" << slices << ") for cone" << endl;
              exit (EXIT_FAILURE);
            }
          const int stacks = std::stoi (argv[5], nullptr, 10);
          if (stacks <= 0)
            {
              cerr << "[generator] invalid stacks(" << stacks << ") for cone" << endl;
              exit (EXIT_FAILURE);
            }
          cerr << "[generator] CONE(radius: " << radius
               << ", height: " << height
               << ", slices: " << slices
               << ", stacks: " << stacks << ")" << endl;
          model_cone_write (out_file_path, radius, height, slices, stacks);
        }
      else if (!strcmp (SPHERE, polygon))
        {
          const float radius = strtof (argv[2], nullptr);
          if (radius <= 0.0)
            {
              cerr << "[generator] invalid radius(" << radius << ") for sphere" << endl;
              exit (EXIT_FAILURE);
            }
          const int slices = std::stoi (argv[3], nullptr, 10);
          if (slices <= 0)
            {
              cerr << "[generator] invalid slices(" << slices << ") for sphere" << endl;
              exit (EXIT_FAILURE);
            }
          const int stacks = std::stoi (argv[4], nullptr, 10);
          if (stacks <= 0)
            {
              cerr << "[generator] invalid stacks(" << stacks << ") for sphere" << endl;
              exit (EXIT_FAILURE);
            }
          cerr << "[generator] SPHERE(radius: " << radius
               << ", slices: " << slices
               << ", stacks: " << stacks << ")"
               << endl;
          model_sphere_write (out_file_path, radius, slices, stacks);
        }
      else if (!strcmp (BEZIER, polygon))
        {
          const int tesselation = std::stoi (argv[3], nullptr, 10);
          if (tesselation <= 0)
            {
              cerr << "[generator] invalid tesselation(" << tesselation << ") for bezier patch" << endl;
              exit (EXIT_FAILURE);
            }
          const char *const input_patch_file_path = argv[2];
          if (!exists (input_patch_file_path))
            {
              cerr << "[generator] file " << input_patch_file_path << " for bezier patch not found" << endl;
              exit (EXIT_FAILURE);
            }
          cerr << "[generator] BEZIER(tesselation: " << tesselation << ", input file: " << input_patch_file_path << ")"
               << endl;
          model_bezier_write (tesselation, input_patch_file_path, out_file_path);
        }
      else
        {
          cerr << "[generator] Unkown object type: " << polygon << endl;
          exit (EXIT_FAILURE);
        }
    }
  return 0;
}
References model_bezier_write(), model_cone_write(), model_cube_write(), model_plane_write(), and model_sphere_write().