Solar System - demo scence: Sphere
Sphere
Generator » Model
Functions
static void model_sphere_vertex (const float r, const float theta, const float phi, unsigned int *pos, float *points)
static void model_sphere_vertices (const float r, const unsigned int slices, const unsigned int stacks, float points[])
vector< array< vec3, 16 > > read_Bezier (string &patch)
template<typename T >
vec4 dec_polynomial (T n)
template<typename T1 , typename T2 , typename T3 >
void mult (const T1 &a, const T2 &b, T3 &r, const int m, const int p, const int q)
void get_curve (const float time, const mat4 &M, const array< vec3, 4 > &control_points, glm::vec3 &pos, glm::vec3 &deriv)
vec3 get_curve (const float time, const mat4 &M, const array< vec3, 4 > &control_points)
auto get_curve (const mat4 &M)
vec3 get_bezier_point (const float u, const float v, const array< vec3, 16 > &P)
vec3 get_bezier_point2 (const float u, const float v, const array< vec3, 16 > &P)
vector< vec3 > get_bezier_surface (array< vec3, 16 > control_points, int int_tesselation)
static unsigned int model_sphere_nVertices (const unsigned int slices, const unsigned int stacks)
void model_sphere_write (const char *filepath, float radius, unsigned int slices, unsigned int stacks)
Variables
const auto Mcr
const auto Mb
Detailed Description
Function Documentation
dec_polynomial()
template<typename T > vec4 dec_polynomial (T n) inline
Definition at line 413 of file generator.cpp.
{
  return {pow (n, 3), pow (n, 2), n, 1};
}
Referenced by get_bezier_point(), and get_bezier_point2().
get_bezier_point()
vec3 get_bezier_point (const float u, const float v, const array< vec3, 16 > & P)
Definition at line 471 of file generator.cpp.
{
  auto MU = Mb * dec_polynomial (u);
  auto B = get_curve (Mb);
  return MU * (
      B ({P[0], P[1], P[2], P[3]}) (v) * mat4x3 (P[0], P[4], P[8], P[12]) +
      B ({P[4], P[5], P[6], P[7]}) (v) * mat4x3 (P[1], P[5], P[9], P[13]) +
      B ({P[8], P[9], P[10], P[11]}) (v) * mat4x3 (P[2], P[6], P[10], P[14]) +
      B ({P[12], P[13], P[14], P[15]}) (v) * mat4x3 (P[3], P[7], P[11], P[15])
  );
}
References dec_polynomial(), get_curve(), and Mb.
Referenced by get_bezier_surface().
get_bezier_point2()
vec3 get_bezier_point2 (const float u, const float v, const array< vec3, 16 > & P)
Definition at line 483 of file generator.cpp.
{
  // B(u,v) = U M P Mᵀ V
  vec4 U = dec_polynomial (u);
  vec4 V = dec_polynomial (v);
  vector<vec3> VMP;
  auto VM = V * glm::transpose (Mb); //1x4x1
  mult (VM, P, VMP, 1, 4, 4);
  vector<vec3> VMPMU;
  auto MU = Mb * U;
  mult (VMP, MU, VMPMU, 1, 4, 1);
  return VMPMU[0];
}
References dec_polynomial(), Mb, and mult().
get_bezier_surface()
vector< vec3 > get_bezier_surface (array< vec3, 16 > control_points, int int_tesselation)
Definition at line 499 of file generator.cpp.
{
  vector<vec3> pontos;
  float float_tesselation = (float) int_tesselation;
  for (int tv = 0; tv < int_tesselation; ++tv)
    {
      float v = (float) tv / float_tesselation;
      for (int tu = 0; tu < int_tesselation; ++tu)
        {
          float u = (float) tu / (float) float_tesselation;
          // triângulo superior
          pontos.push_back (get_bezier_point ((u + (1.0f / float_tesselation)), (v + (1.0f
                                                                                      / float_tesselation)), control_points));
          pontos.push_back (get_bezier_point (u, (v + (1.0f / float_tesselation)), control_points));
          pontos.push_back (get_bezier_point (u, v, control_points));
          // triângulo inferior
          pontos.push_back (get_bezier_point (u, v, control_points));
          pontos.push_back (get_bezier_point ((u + (1.0f / float_tesselation)), v, control_points));
          pontos.push_back (get_bezier_point ((u + (1.0f / float_tesselation)), (v + (1.0f
                                                                                      / float_tesselation)), control_points));
        }
    }
  return pontos;
}
References get_bezier_point().
get_curve() [1/3]
vec3 get_curve (const float time, const mat4 & M, const array< vec3, 4 > & control_points)
Definition at line 452 of file generator.cpp.
{
  vec3 pos;
  vec3 _;
  get_curve (time, M, control_points, pos, _);
  return pos;
}
References get_curve().
get_curve() [2/3]
void get_curve (const float time, const mat4 & M, const array< vec3, 4 > & control_points, glm::vec3 & pos, glm::vec3 & deriv)
Definition at line 441 of file generator.cpp.
{
  const auto t = glm::vec4 (pow (time, 3), pow (time, 2), time, 1);
  const auto t_prime = glm::vec4 (3 * pow (time, 2), 2 * time, 1, 0);
  mat4x3 K (control_points[0], control_points[1], control_points[2], control_points[3]);
  const auto KM = K * M;
  pos = KM * t;
  deriv = KM * t_prime;
}
Referenced by get_bezier_point(), and get_curve().
get_curve() [3/3]
auto get_curve (const mat4 & M)
Definition at line 460 of file generator.cpp.
{
  return [&M] (const array<vec3, 4> &control_points)
  {
    return [&M, &control_points] (const float time) -> vec3
    {
      return get_curve (time, M, control_points);
    };
  };
}
References get_curve().
model_sphere_nVertices()
static unsigned int model_sphere_nVertices (const unsigned int slices, const unsigned int stacks) inline static
Definition at line 531 of file generator.cpp.
{
  return slices * stacks * 6;
}
Referenced by model_sphere_write().
model_sphere_vertex()
static void model_sphere_vertex (const float r, const float theta, const float phi, unsigned int * pos, float * points) inline static
Definition at line 281 of file generator.cpp.
{
  /*
      x = r ⋅ sin(θ)cos(φ)
      y = r ⋅ sin(φ)
      z = r ⋅ cos(θ)cos(φ)
      r ≥ 0
      θ ∈ {-π +   i⋅s : s = 2π/slices ∧ i ∈ {0,...,slices} }
      ϕ ∈ {-π/2 + j⋅t : t =  π/stacks ∧ j ∈ {0,...,stacks} }
      check
          1. https://www.math3d.org/EumEEZBKe
          2. https://www.math3d.org/zE4n6xayX
   */
  points_vertex (r * sin (theta) * cos (phi), r * sin (phi), r * cos (theta) * cos (phi), pos, points);
}
References points_vertex().
Referenced by model_sphere_vertices().
model_sphere_vertices()
static void model_sphere_vertices (const float r, const unsigned int slices, const unsigned int stacks, float points[]) static
Definition at line 299 of file generator.cpp.
{
  // https://www.math3d.org/EumEEZBKe
  // https://www.math3d.org/zE4n6xayX
  const float s = 2.0f * (float) M_PI / (float) slices;
  const float t = M_PI / (float) stacks;
  const float theta = -M_PI;
  const float phi = -M_PI / 2.0f;
  unsigned int pos = 0;
  for (unsigned int m = 1; m <= slices; m++)
    {
      for (unsigned int n = 1; n <= stacks; n++)
        {
          float i = (float) m;
          float j = (float) n;
          model_sphere_vertex (r, theta + s * (i - 1), phi + t * j, &pos, points); // P1'
          model_sphere_vertex (r, theta + s * i, phi + t * (j - 1), &pos, points); // P2
          model_sphere_vertex (r, theta + s * i, phi + t * j, &pos, points); //P2'
          model_sphere_vertex (r, theta + s * (i - 1), phi + t * (j - 1), &pos, points); // P1
          model_sphere_vertex (r, theta + s * i, phi + t * (j - 1), &pos, points); // P2
          model_sphere_vertex (r, theta + s * (i - 1), phi + t * j, &pos, points); // P1'
        }
    }
}
References model_sphere_vertex().
Referenced by model_sphere_write().
model_sphere_write()
void model_sphere_write (const char * filepath, float radius, unsigned int slices, unsigned int stacks)
Definition at line 536 of file generator.cpp.
{
  const unsigned int nVertices = model_sphere_nVertices (slices, stacks);
  float points[3 * nVertices];
  model_sphere_vertices (radius, slices, stacks, points);
  points_write (filepath, nVertices, points);
}
References model_sphere_nVertices(), model_sphere_vertices(), and points_write().
Referenced by main().
mult()
template<typename T1 , typename T2 , typename T3 > void mult (const T1 & a, const T2 & b, T3 & r, const int m, const int p, const int q)
Parameters
a a[m][p]
b b[p][q]
[out] r r[m][q]
m
q
p
Definition at line 426 of file generator.cpp.
{
  for (auto i = 0; i < m; ++i)
    {
      for (auto j = 0; j < q; ++j)
        {
          r[m * i + j] *= 0;
          for (auto k = 0; k < p; k++)
            {
              r[m * i + j] += a[m * i + k] * b[p * k + j];
            }
        }
    }
}
Referenced by get_bezier_point2().
read_Bezier()
vector< array< vec3, 16 > > read_Bezier (string & patch)
Definition at line 347 of file generator.cpp.
{
  string buffer;
  ifstream myFile;
  myFile.open (patch, ios::in | ios::out);
  getline (myFile, buffer);
  // Número de patches presentes no ficheiro.
  int n_patches = stoi (buffer);
  // Vetor de vetores de índices.
  vector<vector<int>> patches;
  // Ciclo externo lê uma linha (patch) de cada vez
  for (int j = 0; j < n_patches; j++)
    {
      vector<int> patchIndexes;
      /*
      Ciclo interno lê os índices dos pontos de controlo de cada patch, sabendo que cada
      patch terá 16 pontos de controlo.
      */
      for (int i = 0; i < 16; i++)
        {
          getline (myFile, buffer, ',');
          patchIndexes.push_back (stoi (buffer));
        }
      patches.push_back (patchIndexes);
    }
  getline (myFile, buffer);
  // Número de pontos presentes no ficheiro.
  int pts = stoi (buffer);
  // Vetor que guardará as coordenadas de pontos de controlo para superfície de Bézier.
  vector<vec3> control;
  for (int j = 0; j < pts; j++)
    {
      vec3 v;
      getline (myFile, buffer, ',');
      v.x = stof (buffer);
      getline (myFile, buffer, ',');
      v.y = stof (buffer);
      getline (myFile, buffer, ',');
      v.z = stof (buffer);
      control.push_back (v);
    }
  /*
  Percorrem-se os vetores que, para cada patch, guardam os seus índices de pontos de controlo.
  Para cada patch, constroi-se um vetor com as coordenadas dos seus pontos de controlo.
  */
  vector<array<vec3, 16>> pointsInPatches;
  for (auto &patche : patches)
    {
      array<vec3, 16> pointsInPatch{};
      for (int j = 0; j < 16; j++)
        {
          pointsInPatch[j] = control[patche[j]];
        }
      pointsInPatches.push_back (pointsInPatch);
    }
  myFile.close ();
  return pointsInPatches;
}
Variable Documentation
Mb
const auto Mb
Initial value:
= mat4 (
    -1, 3, -3, 1,
    3, -6, 3, 0,
    -3, 3, 0, 0,
    1, 0, 0, 0)
Definition at line 341 of file generator.cpp.
Referenced by get_bezier_point(), and get_bezier_point2().
Mcr
const auto Mcr
Initial value:
= mat4 (
    -0.5f, 1.5f, -1.5f, 0.5f,
    1.0f, -2.5f, 2.0f, -0.5f,
    -0.5f, 0.0f, 0.5f, 0.0f,
    0.0f, 1.0f, 0.0f, 0.0f)
Definition at line 335 of file generator.cpp.