Solar System - demo scence: ExplorerCamera
ExplorerCamera
Engine » Camera
Modules
Position
LookAt
Up
Projection
Functions
void explCamera ()
void explKeyboard (unsigned char key, int x, int y)
void explMouse (int button, int state, int x, int y)
void explMotion (int x, int y)
void explTimer (int)
void env_load_defaults ()
void spherical2Cartesian (const double radius, const double elevation, const double azimuth, double *x, double *y, double *z)
void cartesian2Spherical (const double x, const double y, const double z, double *radius, double *azimuth, double *elevation)
void explRedisplay ()
Variables
const profile_t globalProfile_EXPL
double DEFAULT_GLOBAL_RADIUS = 1
double DEFAULT_GLOBAL_AZIMUTH = 0
double DEFAULT_GLOBAL_ELEVATION = 0
double globalRadius = DEFAULT_GLOBAL_RADIUS
double globalAzimuth = DEFAULT_GLOBAL_AZIMUTH
double globalElevation = DEFAULT_GLOBAL_ELEVATION
bool globalMouseLeftButton = false
int globalExplXPrev = 0
int globalExplYPrev = 0
Detailed Description
Function Documentation
cartesian2Spherical()
void cartesian2Spherical (const double x, const double y, const double z, double * radius, double * azimuth, double * elevation)
Definition at line 438 of file engine.cpp.
{
  // https://www.wikiwand.com/en/Spherical_coordinate_system
  *radius = abs (sqrt (pow ((x - globalCenterX), 2) + pow ((y - globalCenterY), 2) + pow ((z - globalCenterZ), 2)));
  *elevation = acos ((y - globalCenterY) / (*radius));
  *azimuth = atan2 ((z - globalCenterZ), (x - globalCenterZ));
}
References globalCenterX, globalCenterY, and globalCenterZ.
Referenced by operations_render().
env_load_defaults()
void env_load_defaults ()
Definition at line 453 of file engine.cpp.
{
  /*rotation*/
  globalAngleStep = DEFAULT_GLOBAL_ANGLE_STEP;
  globalAngle = 0;
  globalRotateX = 0;
  globalRotateY = 0;
  globalRotateZ = 0;
  /*translation*/
  globalTranslateStep = DEFAULT_GLOBAL_TRANSLATE_STEP;
  globalTranslateX = 0;
  globalTranslateY = 0;
  globalTranslateZ = 0;
  /*scaling*/
  globalScaleStep = DEFAULT_GLOBAL_SCALE_STEP;
  globalScaleX = 1;
  globalScaleY = 1;
  globalScaleZ = 1;
  /*position*/
  globalEyeStep = DEFAULT_GLOBAL_EYE_STEP;
  globalEyeX = DEFAULT_GLOBAL_EYE_X;
  globalEyeY = DEFAULT_GLOBAL_EYE_Y;
  globalEyeZ = DEFAULT_GLOBAL_EYE_Z;
  globalRadius = DEFAULT_GLOBAL_RADIUS;
  globalAzimuth = DEFAULT_GLOBAL_AZIMUTH;
  globalElevation = DEFAULT_GLOBAL_ELEVATION;
  /*lookAt*/
  globalCenterStep = DEFAULT_GLOBAL_CENTER_STEP;
  globalCenterX = DEFAULT_GLOBAL_CENTER_X;
  globalCenterY = DEFAULT_GLOBAL_CENTER_Y;
  globalCenterZ = DEFAULT_GLOBAL_CENTER_Z;
  /*up*/
  globalUpStep = DEFAULT_GLOBAL_UP_STEP;
  globalUpX = DEFAULT_GLOBAL_UP_X;
  globalUpY = DEFAULT_GLOBAL_UP_Y;
  globalUpZ = DEFAULT_GLOBAL_UP_Z;
  /*projection*/
  globalFOV = DEFAULT_GLOBAL_FOV;
  globalNear = DEFAULT_GLOBAL_NEAR;
  globalFar = DEFAULT_GLOBAL_FAR;
}
References DEFAULT_GLOBAL_ANGLE_STEP, DEFAULT_GLOBAL_AZIMUTH, DEFAULT_GLOBAL_CENTER_STEP, DEFAULT_GLOBAL_CENTER_X, DEFAULT_GLOBAL_CENTER_Y, DEFAULT_GLOBAL_CENTER_Z, DEFAULT_GLOBAL_ELEVATION, DEFAULT_GLOBAL_EYE_STEP, DEFAULT_GLOBAL_EYE_X, DEFAULT_GLOBAL_EYE_Y, DEFAULT_GLOBAL_EYE_Z, DEFAULT_GLOBAL_FAR, DEFAULT_GLOBAL_FOV, DEFAULT_GLOBAL_NEAR, DEFAULT_GLOBAL_RADIUS, DEFAULT_GLOBAL_SCALE_STEP, DEFAULT_GLOBAL_TRANSLATE_STEP, DEFAULT_GLOBAL_UP_STEP, DEFAULT_GLOBAL_UP_X, DEFAULT_GLOBAL_UP_Y, DEFAULT_GLOBAL_UP_Z, globalAngle, globalAngleStep, globalAzimuth, globalCenterStep, globalCenterX, globalCenterY, globalCenterZ, globalElevation, globalEyeStep, globalEyeX, globalEyeY, globalEyeZ, globalFar, globalFOV, globalNear, globalRadius, globalRotateX, globalRotateY, globalRotateZ, globalScaleStep, globalScaleX, globalScaleY, globalScaleZ, globalTranslateStep, globalTranslateX, globalTranslateY, globalTranslateZ, globalUpStep, globalUpX, globalUpY, and globalUpZ.
Referenced by explKeyboard(), and xml_load_and_set_env().
explCamera()
void explCamera ()
Definition at line 833 of file engine.cpp.
{
  // set the camera
  gluLookAt (globalEyeX, globalEyeY, globalEyeZ,
             globalCenterX, globalCenterY, globalCenterZ,
             globalUpX, globalUpY, globalUpZ);
  //draw_axes ();
  // put the geometric transformations here
  glRotatef (globalAngle, globalRotateX, globalRotateY, globalRotateZ);
  glTranslatef (globalTranslateX, globalTranslateY, globalTranslateZ);
  glScalef (globalScaleX, globalScaleY, globalScaleZ);
}
References globalAngle, globalCenterX, globalCenterY, globalCenterZ, globalEyeX, globalEyeY, globalEyeZ, globalRotateX, globalRotateY, globalRotateZ, globalScaleX, globalScaleY, globalScaleZ, globalTranslateX, globalTranslateY, globalTranslateZ, globalUpX, globalUpY, and globalUpZ.
explKeyboard()
void explKeyboard (unsigned char key, int x, int y)
Definition at line 503 of file engine.cpp.
{
  /*
      Rotation:
          x y z       x y z
          X Y Z       x y z
      angle:
          , .     -=s    +=s
          < >     s     s
      translation:
          q w e       y z y
          a s d       x z x
      scaling:
          u i o       y z y
          j k l       x z x
      background color: r g b R G B
      camera:
          1 2 3        ! @ #         EyeX     EyeY     EyeZ
          4 5 6       $ % ^        CenterX  CenterY  CenterZ
          7 8 9        & * (         UpX      UpY      UpZ
   */
  const unsigned char ESC = 27;
  switch (key)
    {
      case ESC:
        {
          globalLockCenter = !globalLockCenter;
          if (globalLockCenter)
            glutSetCursor (GLUT_CURSOR_NONE);
          else
            glutSetCursor (GLUT_CURSOR_CROSSHAIR);
          break;
        }
      /*Rotation*/
      case 'x':
        globalRotateX -= 1;
      break;
      case 'X':
        globalRotateX += 1;
      break;
      case 'y':
        globalRotateY -= 1;
      break;
      case 'Y':
        globalRotateY += 1;
      break;
      case 'z':
        globalRotateZ -= 1;
      break;
      case 'Z':
        globalRotateZ += 1;
      break;
      case ',':
        globalAngle -= globalAngleStep;
      break;
      case '.':
        globalAngle += globalAngleStep;
      break;
      case '<':
        globalAngleStep /= 2;
      break;
      case '>':
        globalAngleStep *= 2;
      break;
      /*translation*/
      case 'T':
        globalTranslateStep *= 2;
      break;
      case 't':
        if (globalTranslateStep > 1)
          globalTranslateStep /= 2;
      break;
      /*z-axis*/
      case 'w':
        globalTranslateZ += globalTranslateStep;
      break;
      case 's':
        globalTranslateZ -= globalTranslateStep;
      break;
      /*x-axis*/
      case 'a':
        globalTranslateX -= globalTranslateStep;
      break;
      case 'd':
        globalTranslateX += globalTranslateStep;
      break;
      /*y-axis*/
      case 'q':
        globalTranslateY -= globalTranslateStep;
      break;
      case 'e':
        globalTranslateY += globalTranslateStep;
      break;
      /*end of translation*/
      /*scaling*/
      /*z-axis*/
      case 'i':
        globalScaleZ += globalScaleStep;
      break;
      case 'k':
        globalScaleZ -= globalScaleStep;
      break;
      /*x-axis*/
      case 'j':
        globalScaleX -= globalScaleStep;
      break;
      case 'l':
        globalScaleX += globalScaleStep;
      break;
      /*y-axis*/
      case 'u':
        globalScaleY -= globalScaleStep;
      break;
      case 'o':
        globalScaleY += globalScaleStep;
      break;
      /*end of scaling*/
      /*camera*/
      case '`':
        globalEyeStep *= 2;
      break;
      case '~':
        if (globalEyeStep > 1)
          globalEyeStep /= 2;
      break;
      case '1':
        globalEyeX -= globalEyeStep;
      break;
      case '!':
        globalEyeX += globalEyeStep;
      break;
      case '2':
        globalEyeY -= globalEyeStep;
      break;
      case '@':
        globalEyeY += globalEyeStep;
      break;
      case '3':
        globalEyeZ -= globalEyeStep;
      break;
      case '#':
        globalEyeZ += globalEyeStep;
      break;
      case '4':
        globalCenterX -= globalCenterStep;
      break;
      case '$':
        globalCenterX += globalCenterStep;
      break;
      case '5':
        globalCenterY -= globalCenterStep;
      break;
      case '%':
        globalCenterY += globalCenterStep;
      break;
      case '6':
        globalCenterZ -= globalCenterStep;
      break;
      case '^':
        globalCenterZ += globalCenterStep;
      break;
      case '7':
        globalUpX -= globalUpStep;
      break;
      case '&':
        globalUpX += globalUpStep;
      break;
      case '8':
        globalUpY -= globalUpStep;
      break;
      case '*':
        globalUpY += globalUpStep;
      break;
      case '9':
        globalUpZ -= globalUpStep;
      break;
      case '(':
        globalUpZ += globalUpStep;
      break;
      /*reset environment*/
      case '0':
        env_load_defaults ();
      break;
      case ' ':
        changeProfile ();
      break;
      default:
        break;
    }
  explRedisplay (); //request display() call ASAP
}
References changeProfile(), env_load_defaults(), explRedisplay(), globalAngle, globalAngleStep, globalCenterStep, globalCenterX, globalCenterY, globalCenterZ, globalEyeStep, globalEyeX, globalEyeY, globalEyeZ, globalLockCenter, globalRotateX, globalRotateY, globalRotateZ, globalScaleStep, globalScaleX, globalScaleY, globalScaleZ, globalTranslateStep, globalTranslateX, globalTranslateY, globalTranslateZ, globalUpStep, globalUpX, globalUpY, and globalUpZ.
explMotion()
void explMotion (int x, int y)
Definition at line 802 of file engine.cpp.
{
  if (globalMouseLeftButton)
    {
      const double stepAlfa = 0.04;
      const double stepBeta = 0.035;
      if (x > globalExplXPrev) // moving mouse right
        globalAzimuth += stepAlfa;
      else if (x < globalExplXPrev) // moving mouse left
        globalAzimuth -= stepAlfa;
      if (y > globalExplYPrev) // moving mouse up
        {
          globalElevation -= stepBeta;
          if (globalElevation < .1)
            globalElevation = .1;
        }
      else if (y < globalExplYPrev) // moving mouse down
        {
          globalElevation += stepBeta;
          if (globalElevation > 3.1)
            globalElevation = 3.1;
        }
      globalExplXPrev = x;
      globalExplYPrev = y;
    }
  explRedisplay ();
}
References explRedisplay(), globalAzimuth, globalElevation, globalExplXPrev, globalExplYPrev, and globalMouseLeftButton.
explMouse()
void explMouse (int button, int state, int x, int y)
Definition at line 721 of file engine.cpp.
{
  // Wheel reports as button 3(scroll up) and button 4(scroll down)
  if ((button == 3) || (button == 4)) // It's a wheel event
    {
      // Each wheel event reports like a button click, GLUT_DOWN then GLUT_UP
      if (state == GLUT_UP)
        return; // Disregard redundant GLUT_UP events
      if (button == 3)
        {
          globalRadius *= .8f;
          if (globalRadius < .1f)
            globalRadius = .1f;
        }
      else
        globalRadius *= 1.5;
      printf ("Scroll %s At %d %d\n", (button == 3) ? "Up" : "Down", x, y);
    }
  else
    {  // normal button event
      printf ("Button %s At %d %d\n", (state == GLUT_DOWN) ? "Down" : "Up", x, y);
      if (button == GLUT_LEFT_BUTTON)
        {
          if (state == GLUT_DOWN)
            {
              globalMouseLeftButton = true;
              globalExplXPrev = x;
              globalExplYPrev = y;
            }
          if (state == GLUT_UP)
            {
              globalMouseLeftButton = false;
            }
        }
      else if (button == GLUT_RIGHT_BUTTON)
        {
          if (state == GLUT_DOWN)
            {
              int window_width = glutGet (GLUT_WINDOW_WIDTH);
              int window_height = glutGet (GLUT_WINDOW_HEIGHT);
              GLbyte color[4];
              GLfloat depth;
              GLuint index;
              //glReadPixels (x, window_height - y - 1, 1, 1, GL_RGBA, GL_UNSIGNED_BYTE, color);
              glReadPixels (x, window_height - y - 1, 1, 1, GL_DEPTH_COMPONENT, GL_FLOAT, &depth);
              //glReadPixels (x, window_height - y - 1, 1, 1, GL_STENCIL_INDEX, GL_UNSIGNED_INT, &index);
              double ox, oy, oz;
              double model[16];
              glGetDoublev (GL_MODELVIEW_MATRIX, model);
              double proj[16];
              glGetDoublev (GL_PROJECTION_MATRIX, proj);
              int view[4];
              glGetIntegerv (GL_VIEWPORT, view);
              gluUnProject (x, window_height - y - 1, depth,
                            model,
                            proj,
                            view,
                            &ox, &oy, &oz);
              fprintf (stderr, "%d %d\n", x, y);
              //globalTranslateX = -ox;
              //globalTranslateZ = -oz;
              /*cartesian2Spherical (ox, globalEyeY, oz,
                                   &globalRadius, &globalAzimuth, &globalElevation);*/
              //              globalTranslateX = ox;
              //              globalTranslateZ = oz;
              globalCenterX = ox;
              globalCenterZ = oz;
              fprintf (stderr, "%f %f %f\n", ox, oy, oz);
            }
        }
    }
  explRedisplay ();
}
References explRedisplay(), globalCenterX, globalCenterZ, globalExplXPrev, globalExplYPrev, globalMouseLeftButton, and globalRadius.
explRedisplay()
void explRedisplay ()
Definition at line 447 of file engine.cpp.
{
  spherical2Cartesian (globalRadius, globalElevation, globalAzimuth, &globalEyeX, &globalEyeY, &globalEyeZ);
  glutPostRedisplay ();
}
References globalAzimuth, globalElevation, globalEyeX, globalEyeY, globalEyeZ, globalRadius, and spherical2Cartesian().
Referenced by explKeyboard(), explMotion(), and explMouse().
explTimer()
void explTimer (int)
Definition at line 846 of file engine.cpp.
{
  glutPostRedisplay ();
}
spherical2Cartesian()
void spherical2Cartesian (const double radius, const double elevation, const double azimuth, double * x, double * y, double * z)
Definition at line 428 of file engine.cpp.
{
  // https://www.wikiwand.com/en/Spherical_coordinate_system
  *x = radius * sin (elevation) * cos (azimuth) + globalCenterX;
  *y = radius * cos (elevation) + globalCenterY;
  *z = radius * sin (elevation) * sin (azimuth) + globalCenterZ;
}
References globalCenterX, globalCenterY, and globalCenterZ.
Referenced by explRedisplay().
Variable Documentation
DEFAULT_GLOBAL_AZIMUTH
double DEFAULT_GLOBAL_AZIMUTH = 0
Definition at line 369 of file engine.cpp.
Referenced by env_load_defaults(), and operations_render().
DEFAULT_GLOBAL_ELEVATION
double DEFAULT_GLOBAL_ELEVATION = 0
Definition at line 370 of file engine.cpp.
Referenced by env_load_defaults(), and operations_render().
DEFAULT_GLOBAL_RADIUS
double DEFAULT_GLOBAL_RADIUS = 1
Definition at line 368 of file engine.cpp.
Referenced by env_load_defaults(), and operations_render().
globalAzimuth
double globalAzimuth = DEFAULT_GLOBAL_AZIMUTH
Definition at line 373 of file engine.cpp.
Referenced by env_load_defaults(), explMotion(), and explRedisplay().
globalElevation
double globalElevation = DEFAULT_GLOBAL_ELEVATION
Definition at line 374 of file engine.cpp.
Referenced by env_load_defaults(), explMotion(), and explRedisplay().
globalExplXPrev
int globalExplXPrev = 0
Definition at line 718 of file engine.cpp.
Referenced by explMotion(), and explMouse().
globalExplYPrev
int globalExplYPrev = 0
Definition at line 719 of file engine.cpp.
Referenced by explMotion(), and explMouse().
globalMouseLeftButton
bool globalMouseLeftButton = false
Definition at line 375 of file engine.cpp.
Referenced by explMotion(), and explMouse().
globalProfile_EXPL
const profile_t globalProfile_EXPL
Initial value:
= {
    .mouseFunc = explMouse,
    .motionFunc = explMotion,
    .keyboardFunc = explKeyboard,
    .reshapeFunc = defaultChangeSize,
    .timerFunc = explTimer,
    .camera = explCamera,
}
Definition at line 359 of file engine.cpp.
globalRadius
double globalRadius = DEFAULT_GLOBAL_RADIUS
Definition at line 372 of file engine.cpp.
Referenced by env_load_defaults(), explMouse(), and explRedisplay().