Solar System - demo scence: Model
Model
Engine
Classes
struct model
Functions
struct model allocModel (const char *const model3dFilePath)
void associate_a_texture_to_model (struct model &m, const char *const path)
void renderModel (const struct model &model)
Variables
const auto RGB_MAX = 255.0
static std::vector< struct model > globalModels
static std::vector< float > globalOperations
Detailed Description
Function Documentation
allocModel()
struct model allocModel (const char *const model3dFilePath)
Definition at line 857 of file engine.cpp.
{
  FILE *fp = fopen (model3dFilePath, "r");
  if (!fp)
    {
      cerr << "failed to open model: " << model3dFilePath << endl;
      exit (EXIT_FAILURE);
    }
  cerr << "[allocModel] model file = " << model3dFilePath << endl;
  // read number of vertices
  GLsizei nVertices;
  fread (&nVertices, sizeof (nVertices), 1, fp);
  cerr << "[allocModel] nVertices = " << nVertices << endl;
  // read vertices
  auto *arrayOfVertices = (float *) malloc (3 * nVertices * sizeof (float));
  const size_t nVerticesRead = fread (arrayOfVertices, 3 * sizeof (float), nVertices, fp);
  if (nVerticesRead != nVertices)
    {
      cerr << nVerticesRead << " = nVerticesRead != nVertices = " << nVertices << endl;
      exit (EXIT_FAILURE);
    }
  // read normals
  auto *arrayOfNormals = (float *) malloc (3 * nVertices * sizeof (float));
  const size_t nNormalsRead = fread (arrayOfNormals, 3 * sizeof (float), nVertices, fp);
  if (nNormalsRead != nVertices)
    {
      cerr << nNormalsRead << " = nNormalsRead != nVertices = " << nVertices << endl;
      exit (EXIT_FAILURE);
    }
  // read texture coordinates
  auto *arrayOfTextureCoordinates = (float *) malloc (2 * nVertices * sizeof (float));
  const size_t nTextureCoordinatesRead = fread (arrayOfTextureCoordinates, 2 * sizeof (float), nVertices, fp);
  if (nTextureCoordinatesRead != nVertices)
    {
      fprintf (stderr, "%zu = nTextureCoordinatesRead != nVertices = %ul", nTextureCoordinatesRead, nVertices);
      exit (EXIT_FAILURE);
    }
  fclose (fp);
  struct model model;
  model.nVertices = nVertices;
  // vertices buffer object array
  const GLsizei sizeOfVertexArray = (GLsizei) sizeof (arrayOfVertices[0]) * 3 * model.nVertices;
  glGenBuffers (1, &model.vbo);
  glBindBuffer (GL_ARRAY_BUFFER, model.vbo);
  glBufferData (GL_ARRAY_BUFFER, sizeOfVertexArray, arrayOfVertices, GL_STATIC_DRAW);
  free (arrayOfVertices);
  // normals buffer object array
  const GLsizei sizeOfNormalsArray = (GLsizei) sizeof (arrayOfNormals[0]) * 3 * model.nVertices;
  glGenBuffers (1, &model.normals);
  glBindBuffer (GL_ARRAY_BUFFER, model.normals);
  glBufferData (GL_ARRAY_BUFFER, sizeOfNormalsArray, arrayOfNormals, GL_STATIC_DRAW);
  free (arrayOfNormals);
  // texture coordinates buffer object array
  const GLsizei sizeOfTextureCoordinateArray = (GLsizei) sizeof (arrayOfVertices[0]) * 2 * model.nVertices;
  glGenBuffers (1, &model.tc);
  glBindBuffer (GL_ARRAY_BUFFER, model.tc);
  glBufferData (GL_ARRAY_BUFFER, sizeOfTextureCoordinateArray, arrayOfTextureCoordinates, GL_STATIC_DRAW);
  free (arrayOfTextureCoordinates);
  // unbind array buffer
  glBindBuffer (GL_ARRAY_BUFFER, 0);
  return model;
}
References model::normals, model::nVertices, model::tc, and model::vbo.
Referenced by operations_render().
associate_a_texture_to_model()
void associate_a_texture_to_model (struct model & m, const char *const path)
Definition at line 931 of file engine.cpp.
{
  static bool isFirstTimeBeingExecuted = true;
  if (isFirstTimeBeingExecuted)
    {
      // DevIL setup - done once (slide 5) [class11]
      ilInit ();
      ilEnable (IL_ORIGIN_SET);
      ilOriginFunc (IL_ORIGIN_LOWER_LEFT);
    }
  // for each image (slide 5) [class11]
  ILuint image;
  ilGenImages (1, &image);
  ilBindImage (image);
  const ILboolean has_loaded_successfully = ilLoadImage ((ILstring) path);
  if (!has_loaded_successfully)
    {
      cerr << "[engine] failed loading texture file '" << path << "'"
           << "\nERROR#" << ilGetError () << endl;
      exit (EXIT_FAILURE);
    }
  // convert to RGBA (slide 6) [class11]
  const ILboolean has_converted_image_sucessfully = ilConvertImage (IL_RGBA, IL_UNSIGNED_BYTE);
  if (!has_converted_image_sucessfully)
    {
      cerr << "[engine] failed to convert texture '" << path << "'" << endl;
      exit (EXIT_FAILURE);
    }
  // texture creation in OpenGL (slide 8) [class11]
  // create a texture slot (slide 8) [class11]
  glGenTextures (1, &m.tbo);
  // bind the slot (slide 8) [class11]
  glBindTexture (GL_TEXTURE_2D, m.tbo);
  // define texture parameters (slide 8) [class11]
  glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
  glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
  glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR_MIPMAP_LINEAR);
  glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
  // get the required info (slide 7) [class11]
  const ILubyte *const texData = ilGetData ();
  const GLsizei texture_width = ilGetInteger (IL_IMAGE_WIDTH);
  const GLsizei texture_height = ilGetInteger (IL_IMAGE_HEIGHT);
  // send texture data to OpenGL (slide 8) [class11]
  glTexImage2D (GL_TEXTURE_2D, 0, GL_RGBA,
                texture_width, texture_height, 0,
                GL_RGBA, GL_UNSIGNED_BYTE, texData);
  glGenerateMipmap (GL_TEXTURE_2D);
  // unbind texture
  glBindTexture (GL_TEXTURE_2D, 0);
  isFirstTimeBeingExecuted = false;
}
References model::tbo.
Referenced by operations_render().
renderModel()
void renderModel (const struct model & model)
Definition at line 996 of file engine.cpp.
{
  if (!model.nVertices % 3)
    {
      fprintf (stderr, "Number of coordinates (%d) is not divisible by 3", model.nVertices);
      exit (1);
    }
  // vertex buffer object (slide 14) [class11]
  glBindBuffer (GL_ARRAY_BUFFER, model.vbo);
  glVertexPointer (3, GL_FLOAT, 0, nullptr);
  // normals (slide 14) [class11]
  glBindBuffer (GL_ARRAY_BUFFER, model.normals);
  glNormalPointer (GL_FLOAT, 0, nullptr);
  // texture coordinates (slide 14) [class11]
  glBindBuffer (GL_ARRAY_BUFFER, model.tc);
  glTexCoordPointer (2, GL_FLOAT, 0, nullptr);
  // texture buffer object (slide 14) [class11]
  glBindTexture (GL_TEXTURE_2D, model.tbo);
  //glPushAttrib (GL_ALL_ATTRIB_BITS);
  // define a material for the object(s) (slide 8) [class9]
  glMaterialfv (GL_FRONT, GL_DIFFUSE, value_ptr (model.material.diffuse));
  glMaterialfv (GL_FRONT, GL_AMBIENT, value_ptr (model.material.ambient));
  glMaterialfv (GL_FRONT, GL_SPECULAR, value_ptr (model.material.specular));
  glMaterialfv (GL_FRONT, GL_EMISSION, value_ptr (model.material.emissive));
  glMaterialf (GL_FRONT, GL_SHININESS, model.material.shininess);
  // drawing
  glDrawArrays (GL_TRIANGLES, 0, model.nVertices);
  //glPopAttrib ();
  // unbind array buffer
  glBindBuffer (GL_ARRAY_BUFFER, 0);
  // unbind texture (slide 10) [class11]
  glBindTexture (GL_TEXTURE_2D, 0);
}
References model::ambient, model::diffuse, model::emissive, model::material, model::normals, model::nVertices, model::shininess, model::specular, model::tbo, model::tc, and model::vbo.
Referenced by operations_render().
Variable Documentation
globalModels
std::vector<struct model> globalModels static
Definition at line 854 of file engine.cpp.
Referenced by operations_render().
globalOperations
std::vector<float> globalOperations static
Definition at line 855 of file engine.cpp.
Referenced by renderScene(), and xml_load_and_set_env().
RGB_MAX
const auto RGB_MAX = 255.0
Definition at line 836 of file engine.cpp.
Referenced by operations_push_any().