Solar System - demo scence: Operations
Operations
Functions
void operations_render (vector< float > &operations)
void crashIfFailedAttributeQuery (const XMLError error, const XMLElement &element, const string &attributeName)
template<typename T >
T getAttribute (const XMLElement &e, const string &attributeName)
int operations_push_string_attribute (const XMLElement &element, vector< float > &operations, string &&attribute_name)
void crashIfFileDoesNotExist (const string &filename, const string &additional_info="")
int elementToEnum (string &&s)
void pushFloatAttributes (const XMLElement &element, vector< float > &operations)
void operations_push_any (const XMLElement *element, vector< float > &operations)
void operations_load_xml (const string &filename, vector< float > &operations)
Detailed Description
Data structure for Operations
⟨nfloat⟩ ::= ⟨float⟩ ∈ [0,1]
⟨nvec3f⟩ ::= ⟨nfloat⟩⟨nfloat⟩⟨nfloat⟩
⟨vec3f⟩  ::= ⟨float⟩⟨float⟩⟨float⟩
⟨operations⟩ ::= ⟨grouping⟩⁺
⟨grouping⟩ ::= ⟨BEGIN_GROUP⟩⟨elem⟩⁺⟨END_GROUP⟩
     ⟨elem⟩ ::= ⟨transformation⟩| ⟨model_loading⟩ | ⟨light⟩
               | ⟨position⟩ | ⟨lookAt⟩ | ⟨up⟩ | ⟨projection⟩
               | ⟨grouping⟩
     ⟨position⟩   ::= ⟨POSITION⟩ ⟨vec3f⟩
     ⟨lookAt⟩     ::= ⟨LOOK_AT⟩ ⟨vec3f⟩
     ⟨up⟩         ::= ⟨UP⟩ ⟨vec3f⟩
     ⟨projection⟩ ::= ⟨PROJECTION⟩ ⟨vec3f⟩
⟨light⟩ ::= ⟨point⟩ | ⟨directional⟩ | ⟨spotlight⟩
    ⟨point⟩        ::= ⟨POINT⟩⟨vec3f⟩
    ⟨directional⟩  ::= ⟨DIRECTIONAL⟩⟨vec3f⟩
    ⟨spotlight⟩    ::= ⟨SPOTLIGHT⟩⟨vec3f⟩⟨vec3f⟩⟨cutoff⟩
    ⟨cutoff⟩       ::= ⟨float⟩ ∈ [0,90] ∪ {180}
⟨transformation⟩ ::= ⟨translation⟩ | ⟨rotation⟩ | ⟨scaling⟩
     ⟨translation⟩ ::= ⟨simple_translation⟩ | ⟨extended_translation⟩
          ⟨simple_translation⟩   ::= ⟨TRANSLATE⟩⟨vec3f⟩
          ⟨extended_translation⟩ ::= ⟨EXTENDED_TRANSLATE⟩⟨time⟩⟨align⟩⟨number_of_points⟩⟨vec3f⟩⁺
              ⟨time⟩             ::= ⟨float⟩
              ⟨align⟩            ::= ⟨bool⟩
              ⟨number_of_points⟩ ::= ⟨int⟩
     ⟨rotation⟩ ::= ⟨simple_rotation⟩ | ⟨extended_rotation⟩
          ⟨simple_rotation⟩ ::= ⟨ROTATE⟩⟨vec3f⟩[angle]
              ⟨angle⟩ ::= ⟨float⟩
          ⟨extended_rotation⟩ ::= ⟨EXTENDED_ROTATE⟩⟨vec3f⟩
     ⟨scaling⟩ ::= ⟨SCALE⟩⟨vec3f⟩
⟨model_loading⟩ ::= ⟨BEGIN_MODEL⟩ ⟨number of characters⟩ ⟨char⟩⁺ [texture] [color] ⟨END_MODEL⟩
     ⟨number of characters⟩ ::= ⟨int⟩
⟨texture⟩ ::= ⟨TEXTURE⟩ ⟨number of characters⟩ ⟨char⟩⁺
⟨color⟩   ::=  (⟨DIFFUSE⟩ | ⟨AMBIENT⟩ | ⟨SPECULAR⟩ | ⟨EMISSIVE⟩) ⟨nvec3f⟩
             | ⟨SHININESS⟩ ⟨shininess_float⟩
     ⟨shininess_float⟩ ::= ⟨float⟩ ∈ [0, 128]
Note: we'll use an array of floats, therefore we will need to cast to char when reading the model filename characters and to int when reading the number of characters.
Function Documentation
crashIfFailedAttributeQuery()
void crashIfFailedAttributeQuery (const XMLError error, const XMLElement & element, const string & attributeName)
Definition at line 77 of file parsing.cpp.
{
  if (!error)
    return;
  cerr << "[parsing] failed parsing attribute " << attributeName << " of element " << element.Value ()
       << "\nError: " << XMLDocument::ErrorIDToName (error) << endl;
  exit (EXIT_FAILURE);
}
Referenced by getAttribute().
crashIfFileDoesNotExist()
void crashIfFileDoesNotExist (const string & filename, const string & additional_info = "")
Definition at line 131 of file parsing.cpp.
{
  if (exists (filename))
    return;
  cerr << "[parsing] Failed loading " << filename << " " << additional_info << endl;
  exit (EXIT_FAILURE);
}
Referenced by operations_push_any().
elementToEnum()
int elementToEnum (string && s)
Definition at line 139 of file parsing.cpp.
{
  map<string, int> m{
      {"translate", TRANSLATE},
      {"rotate", ROTATE},
      {"scale", SCALE},
      {"model", MODEL},
      {"texture", TEXTURE},
      {"diffuse", DIFFUSE},
      {"ambient", AMBIENT},
      {"specular", SPECULAR},
      {"emissive", EMISSIVE},
      {"shininess", SHININESS},
      //{"point", POINT}, //conflicts with point in extended translate
      {"directional", DIRECTIONAL},
      {"spotlight", SPOTLIGHT},
      {"position", POSITION},
      {"lookAt", LOOK_AT},
      {"up", UP},
      {"projection", PROJECTION},
      {"group", GROUP},
      {"generator", GENERATOR},
      {"light", LIGHT}
  };
  if (m.count (s))
    return m[s];
  else
    return OTHER;
}
References AMBIENT, DIFFUSE, DIRECTIONAL, EMISSIVE, GENERATOR, GROUP, LIGHT, LOOK_AT, MODEL, OTHER, POSITION, PROJECTION, ROTATE, SCALE, SHININESS, SPECULAR, SPOTLIGHT, TEXTURE, TRANSLATE, and UP.
Referenced by operations_push_any().
getAttribute()
template<typename T > T getAttribute (const XMLElement & e, const string & attributeName)
Definition at line 87 of file parsing.cpp.
{
  T _attributeValue;
  XMLError error;
  if constexpr(std::is_same<string, T>::value)
    {
      const char **attributeValue;
      error = e.QueryStringAttribute (attributeName.c_str (), attributeValue);
      _attributeValue = string{*attributeValue};
    }
  else if constexpr(std::is_same<float, T>::value)
    {
      float attributeValue;
      error = e.QueryFloatAttribute (attributeName.c_str (), &attributeValue);
      _attributeValue = attributeValue;
    }
  else if constexpr(std::is_same<bool, T>::value)
    {
      bool attributeValue;
      error = e.QueryBoolAttribute (attributeName.c_str (), &attributeValue);
      _attributeValue = attributeValue;
    }
  crashIfFailedAttributeQuery (error, e, attributeName);
  return _attributeValue;
}
References crashIfFailedAttributeQuery().
operations_load_xml()
void operations_load_xml (const string & filename, vector< float > & operations)
Definition at line 353 of file parsing.cpp.
{
  XMLDocument doc;
  if (doc.LoadFile (filename.c_str ()))
    {
      cerr << "[parsing] Failed loading file: '" << filename << "'"
           << "\n\tERROR: " << doc.ErrorName () << endl;
      exit (EXIT_FAILURE);
    }
  cerr << "[parsing] Loaded file: '" << filename << "'" << endl;
  const XMLElement *const world = doc.FirstChildElement ("world");
  operations_push_any (world, operations);
}
References operations_push_any().
Referenced by xml_load_and_set_env().
operations_push_any()
void operations_push_any (const XMLElement * element, vector< float > & operations)
Definition at line 182 of file parsing.cpp.
{
  static string generatorExecutable;
  static bool isUsingGenerator = false;
  do
    {
      auto elementEnum = elementToEnum (element->Value ());
      switch (elementEnum)
        {
          case GROUP:
            {
              switch (element->ClosingType ())
                {
                  case XMLElement::OPEN:
                    operations.push_back (BEGIN_GROUP);
                  break;
                  case XMLElement::CLOSED:
                    break;
                  case XMLElement::CLOSING:
                    operations.push_back (END_GROUP); //never happens...i think
                  break;
                }
              break;
            }
          case GENERATOR:
            {
              if (element->Attribute ("dir"))
                {
                  generatorExecutable = getAttribute<string> (*element, "dir");
                  crashIfFileDoesNotExist (generatorExecutable);
                  cerr << "[parsing] using generator " << generatorExecutable << endl;
                  isUsingGenerator = true;
                }
              else if (isUsingGenerator)
                {
                  auto generator_argv = getAttribute<string> (*element, "argv");
                  std::stringstream command;
                  command << std::filesystem::current_path ()
                          << "/" << generatorExecutable << " " << generator_argv;
                  if (system (command.str ().data ()))
                    {
                      cerr << "[parsing] generator failed at line " << element->GetLineNum () << endl;
                      exit (EXIT_FAILURE);
                    }
                }
              break;
            }
          case MODEL:
            {
              switch (element->ClosingType ())
                {
                  case XMLElement::OPEN:
                    operations.push_back (BEGIN_MODEL);
                  case XMLElement::CLOSED:
                    operations_push_string_attribute (*element, operations, "file");
                  break;
                  case XMLElement::CLOSING: // never happens...i think
                    operations.push_back (END_MODEL);
                  break;
                }
              break;
            }
          case ROTATE:
            {
              if (element->Attribute ("time"))
                operations.push_back (EXTENDED_ROTATE);
              else
                operations.push_back (ROTATE);
              pushFloatAttributes (*element, operations);
              break;
            }
          case TRANSLATE:
            {
              switch (element->ClosingType ())
                {
                  // ⟨extended_translation⟩ ::= ⟨EXTENDED_TRANSLATE⟩⟨time⟩⟨align⟩⟨number_of_points⟩⟨vec3f⟩⁺
                  case XMLElement::OPEN:
                    {
                      operations.push_back (EXTENDED_TRANSLATE);
                      auto time = getAttribute<float> (*element, "time");
                      auto align = getAttribute<bool> (*element, "align");
                      operations.insert (operations.end (), {time, (float) align});
                      operations.push_back (0); // create space to insert the number of points
                      auto index_of_number_of_points = operations.size () - 1;
                      auto number_of_points = 0;
                      for (auto child = element->FirstChildElement ("point"); child;
                           child = child->NextSiblingElement ("point"))
{
                          ++number_of_points;
                          pushFloatAttributes (*child, operations);
                        }
                      operations[index_of_number_of_points] = (float) number_of_points;
                    }
                  break;
                  // ⟨simple_translation⟩ ::= ⟨TRANSLATE⟩⟨vec3f⟩
                  case XMLElement::CLOSED:
                    {
                      operations.push_back (TRANSLATE);
                      pushFloatAttributes (*element, operations);
                    }
                  break;
                  case XMLElement::CLOSING:
                    break;
                }
              break;
            }
          case TEXTURE:     // ⟨texture⟩ ::= ⟨TEXTURE⟩ ⟨number of characters⟩ ⟨char⟩⁺
            {
              operations.push_back (elementEnum);
              operations_push_string_attribute (*element, operations, "file");
              break;
            }
          // (⟨DIFFUSE⟩ | ⟨AMBIENT⟩ | ⟨SPECULAR⟩ | ⟨EMISSIVE⟩) ⟨nvec3f⟩
          case DIFFUSE:
          case AMBIENT:
          case SPECULAR:
          case EMISSIVE:
            {
              operations.push_back (elementEnum);
              const float RGB_MAX = 255.0f;
              auto R = getAttribute<float> (*element, "R");
              auto G = getAttribute<float> (*element, "G");
              auto B = getAttribute<float> (*element, "B");
              assert (R >= 0 && G >= 0 && B >= 0);
              assert (R <= RGB_MAX && G <= RGB_MAX && B <= RGB_MAX);
              operations.insert (operations.end (), {R / RGB_MAX, G / RGB_MAX, B / RGB_MAX});
              break;
            }
          case LIGHT: // ⟨point⟩ | ⟨directional⟩ | ⟨spotlight⟩
            {
              elementEnum = elementToEnum (getAttribute<string> (*element, "type"));
              if (elementEnum == OTHER)
                elementEnum = POINT;
            }
          case SHININESS:           // SHININESS⟩ ⟨float ∈ [0, 128]⟩
          case SCALE:               // ⟨scaling⟩ ::= ⟨SCALE⟩⟨vec3f⟩
          case POINT:               // ⟨point⟩        ::= ⟨POINT⟩⟨vec3f⟩
          case DIRECTIONAL:         // ⟨directional⟩  ::= ⟨DIRECTIONAL⟩⟨vec3f⟩
          case SPOTLIGHT:           // ⟨spotlight⟩    ::= ⟨SPOTLIGHT⟩⟨vec3f⟩⟨vec3f⟩⟨cutoff⟩
          case POSITION:            // ⟨position⟩   ::= ⟨POSITION⟩ ⟨vec3f⟩
          case LOOK_AT:             // ⟨lookAt⟩     ::= ⟨LOOK_AT⟩ ⟨vec3f⟩
          case UP:                  // ⟨up⟩         ::= ⟨UP⟩ ⟨vec3f⟩
          case PROJECTION:          // ⟨projection⟩ ::= ⟨PROJECTION⟩ ⟨vec3f⟩
            {
              operations.push_back (elementEnum);
              pushFloatAttributes (*element, operations);
            }
          break;
        }
      auto child = element->FirstChildElement ();
      if (child != nullptr)
        operations_push_any (child, operations);
      switch (elementEnum)
        {
          case MODEL:
            if (element->ClosingType () == tinyxml2::XMLElement::OPEN)
              operations.push_back (END_MODEL);
          break;
          case GROUP:
            operations.push_back (END_GROUP);
          break;
        }
    }
  while ((element = element->NextSiblingElement ()) != nullptr);
}
References AMBIENT, BEGIN_GROUP, BEGIN_MODEL, crashIfFileDoesNotExist(), DIFFUSE, DIRECTIONAL, elementToEnum(), EMISSIVE, END_GROUP, END_MODEL, EXTENDED_ROTATE, EXTENDED_TRANSLATE, GENERATOR, GROUP, LIGHT, LOOK_AT, MODEL, operations_push_any(), operations_push_string_attribute(), OTHER, POINT, POSITION, PROJECTION, pushFloatAttributes(), RGB_MAX, ROTATE, SCALE, SHININESS, SPECULAR, SPOTLIGHT, TEXTURE, TRANSLATE, and UP.
Referenced by operations_load_xml(), and operations_push_any().
operations_push_string_attribute()
int operations_push_string_attribute (const XMLElement & element, vector< float > & operations, string && attribute_name)
Definition at line 115 of file parsing.cpp.
{
  auto element_attribute_value = getAttribute<string> (element, attribute_name);
  int i = 0;
  do
    operations.push_back (element_attribute_value[i++]);
  while (element_attribute_value[i]);
  // add number of characters of element attribute string value
  operations.insert (operations.end () - i, (float) i);
  return i;
}
Referenced by operations_push_any().
operations_render()
void operations_render (vector< float > & operations)
See Operations for the BNF of operations.
Definition at line 1110 of file engine.cpp.
{
  static bool isFirstTimeBeingExecuted = true;
  static bool hasPushedModels = false;
  static bool hasLoadedCurves = false;
  static vector<vector<vec3>> curves;
  static const float amb[4] = {0, 0, 0, 1};
  static const float spec[4] = {1, 1, 1, 1};
  static const float diff[4] = {1, 1, 1, 1};
  unsigned int model_num = 0;
  unsigned char nLights = 0;
  for (unsigned int i = 0; i < operations.size (); ++i)
    {
      assert(nLights < 8);
      switch ((int) operations[i])
        {
          case POSITION:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::cartesian[0] = operations[i + 1];
                  D::cartesian[1] = operations[i + 2];
                  D::cartesian[2] = operations[i + 3];
                  cerr << "POSITION(" << to_string (D::cartesian) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case LOOK_AT:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::origin = {operations[i + 1],
                               operations[i + 2],
                               operations[i + 3]};
                  cerr << "LOOK_AT(" << to_string (D::origin) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case UP:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::up = {operations[i + 1],
                           operations[i + 2],
                           operations[i + 3]};
                  cerr << "UP(" << to_string (D::up) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case PROJECTION:
            {
              if (isFirstTimeBeingExecuted)
                {
                  D::projection = {operations[i + 1],
                                   operations[i + 2],
                                   operations[i + 3]};
                  cerr << "PROJECTION(FOV: " << D::projection.x
                      << ", NEAR: " << D::projection.y
                      << ", FAR: " << D::projection.z
                      << ")" << endl;
                }
              i += 3;
            }
          continue;
          // transformations
          case ROTATE:
            {
              const float rotation_angle = operations[i + 1];
              const vec3 axis_of_rotation (operations[i + 2],
                                           operations[i + 3],
                                           operations[i + 4]);
              glRotatef (operations[i + 1],
                         operations[i + 2],
                         operations[i + 3],
                         operations[i + 4]);
              if (isFirstTimeBeingExecuted)
                cerr << "ROTATE (" << "rotation_angle:" << rotation_angle
                    << ", axis of rotatation: " << to_string (axis_of_rotation) << ")" << endl;
              i += 4; //angle, axis_of_rotation}
            }
          continue;
          case EXTENDED_ROTATE:
            {
              const float rotation_time = operations[i + 1];
              const vec3 axis_of_rotation = {
                  operations[i + 2],
                  operations[i + 3],
                  operations[i + 4]
              };
              advance_in_rotation (rotation_time, axis_of_rotation);
              i += 4; //time, axis_of_rotation
              if (isFirstTimeBeingExecuted)
                cerr << "EXTENDED_ROTATE (rotation_time: " << rotation_time
                    << " seconds, axis_of_rotation: " << to_string (axis_of_rotation) << ")" << endl;
            }
          continue;
          case TRANSLATE:
            {
              const vec3 translation (operations[i + 1],
                                      operations[i + 2],
                                      operations[i + 3]);
              glTranslatef (translation[0],
                            translation[1],
                            translation[2]);
              if (isFirstTimeBeingExecuted)
                cerr << "TRANSLATE (" << to_string (translation) << ")" << endl;
              i += 3;
            }
          continue;
          case EXTENDED_TRANSLATE:
            {
              const int number_of_points = (int) operations[i + 3];
              if (!hasLoadedCurves)
                {
                  vector<vec3> new_curve (number_of_points);
                  for (int j = 0; j < number_of_points; ++j)
                    {
                      const int idx = 3 * j;
                      new_curve.at (j)[0] = operations[i + 4 + idx];
                      new_curve.at (j)[1] = operations[i + 4 + idx + 1];
                      new_curve.at (j)[2] = operations[i + 4 + idx + 2];
                    }
                  curves.push_back (new_curve);
                }
              auto curve = curves.back ();
              renderCurve (Mcr, curve);
              const float translation_time = operations[i + 1];
              const bool align = (bool) operations[i + 2];
              advance_in_curve (translation_time, align, Mcr, curves.back ());
              if (isFirstTimeBeingExecuted)
                cerr << "EXTENDED_TRANSLATE ("
                    << "translation_time: " << translation_time
                    << ", align: " << align
                    << ", number of points: " << number_of_points
                    << ")" << endl;
              i += 3 + number_of_points * 3; // 3 - time,align,number_of_points,points...
            }
          continue;
          case SCALE:
            {
              const vec3 scale (operations[i + 1],
                                operations[i + 2],
                                operations[i + 3]);
              glScalef (scale[0],
                        scale[1],
                        scale[2]);
              if (isFirstTimeBeingExecuted)
                cerr << "SCALE (" << to_string (scale) << ")" << endl;
              i += 3;
            }
          continue;
          // grouping
          case BEGIN_GROUP:
            {
              if (isFirstTimeBeingExecuted)
                cerr << "BEGIN_GROUP" << endl;
              //glPushAttrib (GL_ALL_ATTRIB_BITS);
              glPushMatrix ();
            }
          continue;
          case END_GROUP:
            {
              if (isFirstTimeBeingExecuted)
                cerr << "END_GROUP" << endl;
              glPopMatrix ();
              //glPopAttrib ();
            }
          continue;
          // texture
          case TEXTURE:
            {
              const int stringSize = (int) operations[i + 1];
              if (!hasPushedModels)
                {
                  char textureFilePath[stringSize + 1];
                  int j;
                  for (j = 0; j < stringSize; ++j)
                    textureFilePath[j] = (char) operations[i + 2 + j];
                  textureFilePath[j] = '\0';
                  addTextureImageToModel (globalModels.back (), textureFilePath);
                  if (isFirstTimeBeingExecuted)
                    cerr << "TEXTURE (" << textureFilePath << ")" << endl;
                }
              i += stringSize + 1; //just to be explicit
            }
          continue;
          // object material components
          case DIFFUSE:
            {
              if (!hasPushedModels)
                {
                  auto &diffuse = globalModels.back ().material.diffuse;
                  diffuse[0] = operations[i + 1];
                  diffuse[1] = operations[i + 2];
                  diffuse[2] = operations[i + 3];
                  cerr << "DIFFUSE (" << to_string (diffuse) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case AMBIENT:
            {
              if (!hasPushedModels)
                {
                  auto &ambient = globalModels.back ().material.ambient;
                  ambient[0] = operations[i + 1];
                  ambient[1] = operations[i + 2];
                  ambient[2] = operations[i + 3];
                  cerr << "AMBIENT (" << to_string (ambient) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case SPECULAR:
            {
              if (!hasPushedModels)
                {
                  auto &specular = globalModels.back ().material.specular;
                  specular[0] = operations[i + 1];
                  specular[1] = operations[i + 2];
                  specular[2] = operations[i + 3];
                  cerr << "SPECULAR (" << to_string (specular) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case EMISSIVE:
            {
              if (!hasPushedModels)
                {
                  auto &emissive = globalModels.back ().material.emissive;
                  emissive[0] = operations[i + 1];
                  emissive[1] = operations[i + 2];
                  emissive[2] = operations[i + 3];
                  cerr << "EMISSIVE (" << to_string (emissive) << ")" << endl;
                }
              i += 3;
            }
          continue;
          case SHININESS:
            {
              if (!hasPushedModels)
                {
                  float shininess = (globalModels.back ().material.shininess = operations[i + 1]);
                  cerr << "SHININESS (" << shininess << ")" << endl;
                }
              i += 1;
            }
          continue;
          // model
          case BEGIN_MODEL:
            {
              int stringSize = (int) operations[i + 1];
              if (!hasPushedModels)
                {
                  char modelName[stringSize + 1];
                  int j;
                  for (j = 0; j < stringSize; ++j)
                    modelName[j] = (char) operations[i + 2 + j];
                  modelName[j] = '\0';
                  globalModels.push_back (getModel (modelName));
                  if (isFirstTimeBeingExecuted)
                    cerr << "BEGIN_MODEL (" << modelName << ")" << endl;
                }
              ++model_num;
              i += stringSize + 1; //just to be explicit
            }
          continue;
          case END_MODEL:
            {
              if (isFirstTimeBeingExecuted)
                cerr << "END_MODEL" << endl;
              renderModel (globalModels[model_num - 1]);
            }
          continue;
          // light sources
          case POINT:
            {
              const vec4 pos = {operations[i + 1],
                                operations[i + 2],
                                operations[i + 3],
                                1.0};
              if (isFirstTimeBeingExecuted)
                {
                  glEnable (GL_LIGHT0 + nLights);
                  glLightfv (GL_LIGHT0 + nLights, GL_AMBIENT, amb);
                  glLightfv (GL_LIGHT0 + nLights, GL_DIFFUSE, diff);
                  glLightfv (GL_LIGHT0 + nLights, GL_SPECULAR, spec);
                  cerr << "POINT (" << to_string (pos) << ")" << endl;
                }
              glLightfv (GL_LIGHT0 + nLights, GL_POSITION, value_ptr (pos));
              ++nLights;
              i += 3;
            }
          continue;
          case DIRECTIONAL:
            {
              const vec4 dir = {operations[i + 1],
                                operations[i + 2],
                                operations[i + 3],
                                0.0};
              if (isFirstTimeBeingExecuted)
                {
                  glEnable (GL_LIGHT0 + nLights);
                  glLightfv (GL_LIGHT0 + nLights, GL_AMBIENT, amb);
                  glLightfv (GL_LIGHT0 + nLights, GL_DIFFUSE, diff);
                  glLightfv (GL_LIGHT0 + nLights, GL_SPECULAR, spec);
                  cerr << "DIRECTIONAL (" << to_string (dir) << ")" << endl;
                }
              glLightfv (GL_LIGHT0 + nLights, GL_POSITION, value_ptr (dir));
              ++nLights;
              i += 3;
            }
          continue;
          case SPOTLIGHT:
            {
              const vec4 pos = {operations[i + 1],
                                operations[i + 2],
                                operations[i + 3],
                                1.0};
              const vec4 dir = {operations[i + 4],
                                operations[i + 5],
                                operations[i + 6],
                                1.0};
              const float cutoff = operations[i + 7];
              if (isFirstTimeBeingExecuted)
                {
                  glEnable (GL_LIGHT0 + nLights);
                  glLightfv (GL_LIGHT0 + nLights, GL_AMBIENT, amb);
                  glLightfv (GL_LIGHT0 + nLights, GL_DIFFUSE, diff);
                  glLightfv (GL_LIGHT0 + nLights, GL_SPECULAR, spec);
                  glLightf (GL_LIGHT0 + nLights, GL_SPOT_CUTOFF, cutoff);
                  cerr << "SPOTLIGHT:"
                          "\n\t(pos: " << to_string (pos) << ")"
                                                             "\n\t(dir: " << to_string (dir) << ")"
                                                                                                "\n\t(cutoff: "
                       << cutoff
                       << ")" << endl;
                }
              glLightfv (GL_LIGHT0 + nLights, GL_POSITION, value_ptr (pos));
              glLightfv (GL_LIGHT0 + nLights, GL_SPOT_DIRECTION, value_ptr (dir));
              ++nLights;
              i += 7;
              continue;
            }
        }
    }
  // default mode uses explorer camera
  if (isFirstTimeBeingExecuted)
    cartesian2Spherical (D::origin, D::cartesian, D::polar);
  hasPushedModels = true;
  hasLoadedCurves = true;
  isFirstTimeBeingExecuted = false;
}
References addTextureImageToModel(), advance_in_curve(), advance_in_rotation(), model::ambient, AMBIENT, BEGIN_GROUP, BEGIN_MODEL, D::cartesian(), cartesian2Spherical(), model::diffuse, DIFFUSE, DIRECTIONAL, model::emissive, EMISSIVE, END_GROUP, END_MODEL, EXTENDED_ROTATE, EXTENDED_TRANSLATE, getModel(), globalModels, LOOK_AT, Mcr, D::origin(), POINT, D::polar(), POSITION, D::projection(), PROJECTION, renderCurve(), renderModel(), ROTATE, D::scale(), SCALE, model::shininess, SHININESS, model::specular, SPECULAR, SPOTLIGHT, TEXTURE, TRANSLATE, D::up(), and UP.
Referenced by renderScene(), and xml_load_and_set_env().
pushFloatAttributes()
void pushFloatAttributes (const XMLElement & element, vector< float > & operations)
Definition at line 169 of file parsing.cpp.
{
  auto attribute = element.FirstAttribute ();
  if (attribute != nullptr)
    do
      {
        float attributeValue;
        if (attribute->QueryFloatValue (&attributeValue) == XML_SUCCESS)
          operations.push_back (attribute->FloatValue ());
      }
    while ((attribute = attribute->Next ()) != nullptr);
}
Referenced by operations_push_any().