Solar System - demo scence: Cone
Cone
Generator » Models
Functions
template<typename T >
requires arithmetic<T>
static void model_cone_vertex (const T r, const T height, const T theta, const T h, vector< vec3 > &vertices)
template<typename T >
requires arithmetic<T>
void model_cone_vertices (const T radius, const T height, const unsigned int slices, const unsigned int stacks, vector< vec3 > &vertices, vector< vec3 > &normals, vector< vec2 > &texture)
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices)
void model_cone_write (const char *const filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
Detailed Description
Function Documentation
model_cone_nVertices()
static unsigned int model_cone_nVertices (const unsigned int stacks, const unsigned int slices) inline static
Definition at line 432 of file generator.cpp.
{
  return slices * stacks * 9;
}
Referenced by model_cone_write().
model_cone_vertex()
template<typename T > requires arithmetic<T> static void model_cone_vertex (const T r, const T height, const T theta, const T h, vector< vec3 > & vertices) inline static
\begin{aligned} x &= r⋅\frac{h}{\textrm{height}} ⋅ \cos(θ)\\[2em] y &= h + \textrm{height}\\[2em] z &= r⋅\frac{h}{\textrm{height}} ⋅ \sin(θ) \end{aligned}
\begin{aligned} r &≥ 0\\ θ &∈ \left\{-π + i⋅s : s = \frac{2π}{\textrm{slices}} ∧ i ∈ \{0,...,\textrm{slices}\} \right\}\\ h &∈ \left\{- \textrm{height} + j⋅t : t = \frac{\textrm{height}}{\textrm{stacks}} ∧ j ∈ \{0,...,\textrm{stacks}\} \right\} \end{aligned}
See the 3d model.
Definition at line 338 of file generator.cpp.
{
  /*
     x = r ⋅ (h/height) ⋅ cos(θ)
     y = 2 ⋅ (height + h)
     z = r ⋅ (h/height) ⋅ sin(θ)
     r ≥ 0
     θ ∈ {-π      + i⋅s : s = 2π/slices      ∧ i ∈ {0,...,slices} }
     h ∈ {-height + j⋅t : t = height/stacks ∧ j ∈ {0,...,stacks} }
     check:
         1. https://www.math3d.org/7oeSkmuns
   */
  vertices.emplace_back (r * h / height * cos (theta), height + h, r * h / height * sin (theta));
}
Referenced by model_cone_vertices().
model_cone_vertices()
template<typename T > requires arithmetic<T> void model_cone_vertices (const T radius, const T height, const unsigned int slices, const unsigned int stacks, vector< vec3 > & vertices, vector< vec3 > & normals, vector< vec2 > & texture)
Definition at line 361 of file generator.cpp.
{
  const T s = 2 * M_PI / (float) slices;
  const T t = height / (float) stacks;
  const T theta_0 = -M_PI;
  const T h_0 = -height;
  auto const fslices = (float) slices;
  auto const fstacks = (float) stacks;
  for (unsigned int slice = 1; slice <= slices; ++slice)
    {
      for (unsigned int stack = 1; stack <= stacks; ++stack)
        {
          auto const fslice = (float) slice;
          auto const fstack = (float) stack;
          //base
          vertices.emplace_back (0, 0, 0); //O
          texture.emplace_back (0, 0);
          normals.emplace_back (0, -1, 0);
          for (auto e : {
              -1.0f,//P1
              .0f //P2
          })
            {
              model_cone_vertex (radius, height, theta_0 + s * (fslice + e), h_0, vertices); //P1
              normals.emplace_back (0, -1, 0);
            }
          texture.emplace_back (-1, 0);
          texture.emplace_back (0, 0);
          int q = 0;
          for (auto e : {
              array<float, 2>{0, -1},
              array<float, 2>{-1, 0},
              array<float, 2>{0, 0},
              array<float, 2>{0, -1},
              array<float, 2>{-1, -1},
              array<float, 2>{-1, 0},
          })
            {
              model_cone_vertex (radius, height,
                                 theta_0 + s * (fslice + e[0]),
                                 h_0 + t * (fstack + e[1]), vertices);
              if (q % 3 == 2)
                {
                  const auto P1 = vertices.end ()[-2];
                  const auto P2 = vertices.end ()[-3];
                  const auto P1_prime = vertices.end ()[-1];
                  for (auto _ = 0; _ < 3; ++_)
                    normals.emplace_back (normalize (cross (P2 - P1_prime, P1 - P1_prime)));
                }
              texture.emplace_back (fslice / fslices, fstack / fstacks);
              ++q;
            }
        }
    }
}
References model_cone_vertex().
Referenced by model_cone_write().
model_cone_write()
void model_cone_write (const char *const filepath, const float radius, const float height, const unsigned int slices, const unsigned int stacks)
Definition at line 437 of file generator.cpp.
{
  const unsigned int nVertices = model_cone_nVertices (stacks, slices);
  vector<vec3> vertices;
  vertices.reserve (nVertices);
  vector<vec3> normals;
  normals.reserve (nVertices);
  vector<vec2> texture;
  texture.reserve (nVertices);
  model_cone_vertices (radius, height, slices, stacks, vertices, normals, texture);
  model_write (filepath, vertices, normals, texture);
}
References model_cone_nVertices(), model_cone_vertices(), and model_write().
Referenced by main().