Solar System - demo scence: D Namespace Reference
D Namespace Reference
Engine » Camera » ExplorerCamera
defaults
Functions
vec4 rotate (0, 0, 0, 0)
vec3 translate (0, 0, 0)
vec3 scale (1, 1, 1)
vec3 cartesian (0, 2, 5)
vec3 origin (0, 0, 0)
vec3 up (0, 1, 0)
vec3 projection (60, 1, 100)
(fov,near,var)
vec3 polar (1, 45, 45)
(radius,zenith,azimuth)
Variables
float eyeStep = 1
float centerStep = 1
float upStep = 1
float angleStep = 16
float translateStep = 1
float scaleStep = 1
Detailed Description
defaults
Function Documentation
cartesian()
vec3 D::cartesian (0 , 2 , 5)
Referenced by env_load_defaults(), operations_render(), and spherical2Cartesian().
origin()
vec3 D::origin (0 , 0 , 0)
Referenced by env_load_defaults(), operations_render(), and spherical2Cartesian().
polar()
vec3 D::polar (1 , 45 , 45)
(radius,zenith,azimuth)
Referenced by env_load_defaults(), operations_render(), and spherical2Cartesian().
projection()
vec3 D::projection (60 , 1 , 100)
(fov,near,var)
Referenced by env_load_defaults(), and operations_render().
rotate()
vec4 D::rotate (0 , 0 , 0 , 0)
Referenced by env_load_defaults().
scale()
vec3 D::scale (1 , 1 , 1)
Referenced by env_load_defaults(), and operations_render().
translate()
vec3 D::translate (0 , 0 , 0)
Referenced by env_load_defaults().
up()
vec3 D::up (0 , 1 , 0)
Referenced by env_load_defaults(), and operations_render().
Variable Documentation
angleStep
float D::angleStep = 16
Definition at line 390 of file engine.cpp.
Referenced by env_load_defaults().
centerStep
float D::centerStep = 1
Definition at line 390 of file engine.cpp.
Referenced by env_load_defaults().
eyeStep
float D::eyeStep = 1
Definition at line 390 of file engine.cpp.
scaleStep
float D::scaleStep = 1
Definition at line 390 of file engine.cpp.
Referenced by env_load_defaults().
translateStep
float D::translateStep = 1
Definition at line 390 of file engine.cpp.
Referenced by env_load_defaults().
upStep
float D::upStep = 1
Definition at line 390 of file engine.cpp.
Referenced by env_load_defaults().