Solar System - demo scence: profile_struct Struct Reference
profile_struct Struct Reference
Engine » Camera » Profile
Public Attributes
void(* mouseFunc)(int button, int state, int x, int y)
void(* motionFunc)(int x, int y)
void(* passiveMotionFunc)(int x, int y)
void(* keyboardFunc)(unsigned char key, int xmouse, int ymouse)
void(* keyboardUpFunc)(unsigned char key, int x, int y)
sets the special keyboard up (key release) callback for the current window.
void(* specialFunc)(int key, int xmouse, int ymouse)
void(* displayFunc)()
void(* reshapeFunc)(int w, int h)
void(* timerFunc)(int)
void(* setSettings)()
void(* camera)()
void(* init)()
Detailed Description
Definition at line 40 of file engine.cpp.
Member Data Documentation
camera
void(* profile_struct::camera) ()
Definition at line 86 of file engine.cpp.
Referenced by renderScene().
displayFunc
void(* profile_struct::displayFunc) () inline
Definition at line 80 of file engine.cpp.
{};
Referenced by loadProfile().
init
void(* profile_struct::init) ()
Definition at line 87 of file engine.cpp.
Referenced by renderScene().
keyboardFunc
void(* profile_struct::keyboardFunc) (unsigned char key, int xmouse, int ymouse) inline
glutKeyboardFunc sets the keyboard callback for the current window. When a user types into the window, each key press generating an ASCII character will generate a keyboard callback. The key callback parameter is the generated ASCII character. The state of modifier keys such as Shift cannot be determined directly; their only effect will be on the returned ASCII data.
Definition at line 76 of file engine.cpp.
{};
Referenced by loadProfile().
keyboardUpFunc
void(* profile_struct::keyboardUpFunc) (unsigned char key, int x, int y) inline
sets the special keyboard up (key release) callback for the current window.
Definition at line 78 of file engine.cpp.
{};
Referenced by loadProfile().
motionFunc
void(* profile_struct::motionFunc) (int x, int y) inline
from: https://www.opengl.org/resources/libraries/glut/spec3/node51.html The motion callback for a window is called when the mouse moves within the window while one or more mouse buttons are pressed.
Definition at line 56 of file engine.cpp.
{};
Referenced by loadProfile().
mouseFunc
void(* profile_struct::mouseFunc) (int button, int state, int x, int y) inline
from https://www.opengl.org/resources/libraries/glut/spec3/node50.html: glutMouseFunc sets the mouse callback for the current window. When a user presses and releases mouse buttons in the window, each press and each release generates a mouse callback.
Definition at line 49 of file engine.cpp.
{};
Referenced by loadProfile().
passiveMotionFunc
void(* profile_struct::passiveMotionFunc) (int x, int y) inline
from https://www.opengl.org/resources/libraries/glut/spec3/node51.html The passive motion callback for a window is called when the mouse moves within the window while no mouse buttons are pressed.
Definition at line 63 of file engine.cpp.
{};
Referenced by loadProfile().
reshapeFunc
void(* profile_struct::reshapeFunc) (int w, int h) inline
Definition at line 81 of file engine.cpp.
{};
Referenced by loadProfile().
setSettings
void(* profile_struct::setSettings) () inline
Definition at line 83 of file engine.cpp.
{};
specialFunc
void(* profile_struct::specialFunc) (int key, int xmouse, int ymouse) inline
Definition at line 79 of file engine.cpp.
{};
Referenced by loadProfile().
timerFunc
void(* profile_struct::timerFunc) (int)
Definition at line 82 of file engine.cpp.
Referenced by loadProfile().
The documentation for this struct was generated from the following file:
src/engine.cpp